In [34]:
import pandas as pd 
import numpy as np

In [35]:
df_vitales_defuncion = pd.read_csv("data\dane\dane_estadisticas_vitales_defunciones_20260219_140526.csv", encoding="utf-8-sig")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\juand\AppData\Local\Temp\ipykernel_28096\93728988.py:1: SyntaxWarning: invalid escape sequence '\d'
  df_vitales_defuncion = pd.read_csv("data\dane\dane_estadisticas_vitales_defunciones_20260219_140526.csv", encoding="utf-8-sig")

FileNotFoundError: [Errno 2] No such file or directory: 'data\\dane\\dane_estadisticas_vitales_defunciones_20260219_140526.csv'

In [ ]:
df_vitales_nacimiento = pd.read_csv("C:\\Users\\juand\\Documents\\seminario_proyecto\\data\\dane\\dane_estadisticas_vitales_nacimientos_20260219_140524.csv", encoding="utf-8-sig")

In [ ]:
df_vacunacion = pd.read_csv("data\salud\coberturas_administrativas_vacunacion_por_departamento_20260219_141538.csv", encoding="utf-8-sig")

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\juand\AppData\Local\Temp\ipykernel_15680\2653441668.py:1: SyntaxWarning: invalid escape sequence '\s'
  df_vacunacion = pd.read_csv("data\salud\coberturas_administrativas_vacunacion_por_departamento_20260219_141538.csv", encoding="utf-8-sig")

In [ ]:
df_moratlidad_mortalidad = pd.read_csv("data\salud\indicadores_mortalidad_morbilidad_por_departamento_municipio_20260219_141557.csv", encoding="utf-8-sig")

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\juand\AppData\Local\Temp\ipykernel_15680\2550645727.py:1: SyntaxWarning: invalid escape sequence '\s'
  df_moratlidad_mortalidad = pd.read_csv("data\salud\indicadores_mortalidad_morbilidad_por_departamento_municipio_20260219_141557.csv", encoding="utf-8-sig")

In [ ]:
df_prestadoras = pd.read_csv("data\salud\prestadores_servicios_salud_por_departamento_20260219_141536.csv", encoding="utf-8-sig")

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\juand\AppData\Local\Temp\ipykernel_15680\19286718.py:1: SyntaxWarning: invalid escape sequence '\s'
  df_prestadoras = pd.read_csv("data\salud\prestadores_servicios_salud_por_departamento_20260219_141536.csv", encoding="utf-8-sig")

In [ ]:
print("Columnas en nacimiento:")
df_vitales_nacimiento.columns

Columnas en df_vitales_defuncion:

Index(['periodo', 'area_nacimiento', 'sitio_parto', 'sexo', 'peso_grs',
       'talla_cms', 'fecha_nacimiento', 'hora_nacimiento',
       'parto_atendido_por', 'tiempo_gestacion', 'numero_consultas_prenatales',
       'tipo_parto', 'multiplicidad_embarazo', 'grupo_sanguineo', 'factor_rh',
       'pertenencia_etnica', 'pueblo_indigena', 'edad_madre',
       'estado_conyugal_madre', 'estudios_madre', 'departamento_residencia',
       'municipio_residencia', 'area_residencia', 'regimen_seguridad_social',
       'eps', 'edad_padre', 'estudios_padre'],
      dtype='str')

In [ ]:


print("Columnas en df_vacuancion:")
df_vacunacion.columns

Columnas en df_vacuancion:

Index(['coddepto', 'departamento', 'a_o', 'biol_gico',
       'cobertura_de_vacunaci_n', 'indicator1_statename', 'indicator1',
       'indicator1_1', 'indicator1_2', 'indicator1_3', 'indicator1_4',
       'indicator1_5'],
      dtype='str')

In [ ]:


print("Columnas en df_moratlidad_mortalidad:")
df_moratlidad_mortalidad.columns

Columnas en df_moratlidad_mortalidad:

Index(['coddepartamento', 'departamento', 'codmunicipio', 'municipio',
       'indicador', 'a_o', 'valor_indicador'],
      dtype='str')

In [ ]:
print("columans de defuncion:")
df_vitales_defuncion.columns

columans de defuncion:

Index(['periodo', 'sitio_defuncion', 'tipo_defuncion', 'fecha_defuncion',
       'sexo', 'estado_conyugal_fallecido', 'edad_fallecido', 'ocupacion',
       'pertenencia_etnica', 'departamento_residencia', 'municipio_residencia',
       'regimen_seguridad_social', 'eps', 'diagnostico', 'area_residencia',
       'ultimo_a_o_estudios_fallecido', 'pueblo_indigena'],
      dtype='str')

In [ ]:


print("Columnas en df_prestadoras:")
df_prestadoras.columns

Columnas en df_prestadoras:

Index(['departamento', 'clase_prestador', 'naturaleza', 'a_o',
       'cantidad_de_prestadores'],
      dtype='str')

In [ ]:
df_muestra_defunciones = pd.read_csv("C:\\Users\\juand\\Documents\\seminario_proyecto\\data\\indicadores\\diagnostico_defunciones_muestra.csv", encoding="utf-8-sig", nrows=100)

In [ ]:
df_muestra_defunciones.head()

,periodo,sitio_defuncion,tipo_defuncion,fecha_defuncion,sexo,estado_conyugal_fallecido,edad_fallecido,ocupacion,pertenencia_etnica,departamento_residencia,municipio_residencia,regimen_seguridad_social,eps,diagnostico,area_residencia,ultimo_a_o_estudios_fallecido,pueblo_indigena
0,I TRIMESTRE 2021,VÍA PÚBLICA,NO FETAL,2021-01-02T00:00:00.000,FEMENINO,ESTABA CASADO(A),43.0,PERSONAL DOMÉSTICO,NINGUNO DE LOS ANTERIORES,PUTUMAYO,SIBUNDOY,SUBSIDIADO,MALLAMAS EPS INDIGENA,FALLA RESPIRATORIA,CABECERA MUNICIPAL,NaN,NaN
1,I TRIMESTRE 2021,HOSPITAL/CLÍNICA,FETAL,2021-01-04T00:00:00.000,MASCULINO,NaN,NaN,NaN,NaN,PUTUMAYO,COLÓN,CONTRIBUTIVO,ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD D...,MUERTE FETAL,RURAL DISPERSO,TÉCNICA PROFESIONAL,NaN
2,I TRIMESTRE 2021,HOSPITAL/CLÍNICA,NO FETAL,2021-01-05T00:00:00.000,MASCULINO,ESTABA CASADO(A),91.0,AGRICULTORES DE CULTIVOS TRANSITORIOS,NINGUNO DE LOS ANTERIORES,PUTUMAYO,SANTIAGO,CONTRIBUTIVO,ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD D...,NEUMONIA POR SOSPECHA COVID,CABECERA MUNICIPAL,NaN,NaN
3,I TRIMESTRE 2021,HOSPITAL/CLÍNICA,NO FETAL,2021-01-06T00:00:00.000,FEMENINO,ESTABA CASADO(A),67.0,HOGAR,NINGUNO DE LOS ANTERIORES,PUTUMAYO,SIBUNDOY,CONTRIBUTIVO,NUEVA EPS SA,INFARTO SUBITO,CABECERA MUNICIPAL,NaN,NaN
4,I TRIMESTRE 2021,HOSPITAL/CLÍNICA,FETAL,2021-01-07T00:00:00.000,INDETERMINADO,NaN,NaN,NaN,NaN,PUTUMAYO,SANTIAGO,SUBSIDIADO,AIC-EPSI-I - ASOCIACION INDIGENA DEL CAUCA AIC...,ABORTO INCOMPELTO,CABECERA MUNICIPAL,MEDIA ACADÉMICA O CLÁSICA,NaN

In [ ]:
import msoffcrypto
import io
import pandas as pd

# 准备一个内存缓冲区存放解密后的文件
decrypted = io.BytesIO()

# 打开加密的Excel文件
with open("data\dane\defunciones-no-fetales2022-cuadro-definitivo-2022.xls", "rb") as f:
    # 加载加密文件
    office_file = msoffcrypto.OfficeFile(f)
    
    # 如果有密码，在这里输入；如果没有密码但有加密，尝试默认密码
    # office_file.load_key(password="your_password_here")
    
    # 尝试解密（如果不知道密码，先尝试无密码解密）
    try:
        office_file.decrypt(decrypted)
    except:
        # 有些文件使用默认密码 'VelvetSweatshop'
        office_file.load_key(password="VelvetSweatshop")
        office_file.decrypt(decrypted)

# 读取解密后的文件
df_vital = pd.read_excel(decrypted)

<>:9: SyntaxWarning: invalid escape sequence '\d'
<>:9: SyntaxWarning: invalid escape sequence '\d'
C:\Users\juand\AppData\Local\Temp\ipykernel_28096\3349028845.py:9: SyntaxWarning: invalid escape sequence '\d'
  with open("data\dane\defunciones-no-fetales2022-cuadro-definitivo-2022.xls", "rb") as f:

In [ ]:
df_vital.head()

,Unnamed: 0,Unnamed: 1
0,NaN,NaN
1,Estadísticas vitales de nacimientos y defuncio...,NaN
2,Defunciones no fetales año 2022,NaN
3,NaN,Total Nacional: 287.251
4,NaN,Indice

In [ ]:
import pandas as pd

# Saltar las primeras 4 filas (donde están los títulos)
df_vital = pd.read_excel(
    "data/dane/defunciones-no-fetales2022p-cuadro-definitivo-ano-corrido-2022pr.xls",
    skiprows=4,  # Ajusta este número según necesites
    engine='xlrd'  # Para archivos .xls
)

print(df_vital.head())

XLRDError: Workbook is encrypted

In [36]:
# Ver qué filas tienen datos útiles
df_raw = pd.read_excel(
    "data/dane/defunciones-no-fetales2022p-cuadro-definitivo-ano-corrido-2022pr.xls",
    header=None,  # No tratar ninguna fila como encabezado
    engine='xlrd'
)

# Mostrar las primeras 15 filas para ver la estructura
print("Estructura del archivo (primeras 15 filas):")
for i in range(min(15, len(df_raw))):
    print(f"Fila {i}: {df_raw.iloc[i, :3].tolist()}")

# Identificar dónde empiezan los datos reales
# (busca la fila que tiene "Total Nacional" u otros encabezados)

XLRDError: Workbook is encrypted

In [58]:
import msoffcrypto
import io
import pandas as pd

# Crear un buffer en memoria para el archivo desencriptado
decrypted_buffer = io.BytesIO()

# Abrir el archivo encriptado
with open("data\dane\defunciones-no-fetales2022-cuadro-definitivo-2022.xls", "rb") as f:
    # Cargar el archivo encriptado
    office_file = msoffcrypto.OfficeFile(f)
    
    # Intentar desencriptar
    # Muchos archivos del DANE usan contraseña vacía o la contraseña por defecto
    try:
        # Primero intentar sin contraseña
        office_file.load_key(password=None)
        office_file.decrypt(decrypted_buffer)
        print("Archivo desencriptado sin contraseña")
    except:
        try:
            # Intentar con contraseña vacía (string vacío)
            office_file.load_key(password="")
            office_file.decrypt(decrypted_buffer)
            print("Archivo desencriptado con contraseña vacía")
        except:
            # Intentar con contraseña por defecto común
            office_file.load_key(password="VelvetSweatshop")
            office_file.decrypt(decrypted_buffer)
            print("Archivo desencriptado con contraseña 'VelvetSweatshop'")

# Ahora leer el archivo desencriptado
df_raw = pd.read_excel(decrypted_buffer, header=None)

# Mostrar las primeras filas para ver la estructura
print("\nEstructura del archivo (primeras 15 filas):")
for i in range(min(15, len(df_raw))):
    print(f"Fila {i}: {df_raw.iloc[i, :3].tolist()}")

<>:9: SyntaxWarning: invalid escape sequence '\d'
<>:9: SyntaxWarning: invalid escape sequence '\d'
C:\Users\juand\AppData\Local\Temp\ipykernel_28096\3118713524.py:9: SyntaxWarning: invalid escape sequence '\d'
  with open("data\dane\defunciones-no-fetales2022-cuadro-definitivo-2022.xls", "rb") as f:

Archivo desencriptado con contraseña 'VelvetSweatshop'

Estructura del archivo (primeras 15 filas):
Fila 0: [nan, nan]
Fila 1: [nan, nan]
Fila 2: ['Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: ['Defunciones no fetales año 2022', nan]
Fila 4: [nan, 'Total Nacional:      287.251']
Fila 5: [nan, 'Indice']
Fila 6: [nan, 'Seleccione …']
Fila 7: [nan, 'Cuadro 1    -  Defunciones por área donde ocurrió la defunción y sexo, según grupos de edad, total nacional']
Fila 8: [nan, 'Cuadro 2    -  Defunciones por persona que certifica la defunción, según departamento, área y sitio donde ocurrió la defunción']
Fila 9: [nan, 'Cuadro 3    -  Defunciones por grupos de edad y sexo, según departamento, municipio y área donde ocurrió la defunción']
Fila 10: [nan, 'Cuadro 4    -  Defunciones por grupos de edad y sexo, según departamento, municipio y área de residencia']
Fila 11: [nan, 'Cuadro 5    -  Defunciones por grupos de edad y sexo, según departamento, municipio de residencia y grupos de causas de defunción \n                         (Lista de causas agrupadas 6/67 CIE-10 de OPS)']
Fila 12: [nan, 'Cuadro 6    -  Defunciones por sitio donde ocurrió la defunción, según departamento de ocurrencia y régimen de seguridad social']
Fila 13: [nan, 'Cuadro 7    -  Defunciones maternas, por grupos de edad, según departamento de residencia y grupos de causas de defunción \n                        (Lista de causas agrupadas 6/67 CIE-10 de OPS)']
Fila 14: [nan, 'Cuadro 8    -  Defunciones maternas por grupos de edad, según lista de causas a 3 caracteres CIE-10']

In [61]:
import msoffcrypto
import io
import pandas as pd

# Desencriptar el archivo
decrypted_buffer = io.BytesIO()
with open("data\dane\defunciones-no-fetales2022-cuadro-definitivo-2022.xls", "rb") as f:
    office_file = msoffcrypto.OfficeFile(f)
    office_file.load_key(password="VelvetSweatshop")
    office_file.decrypt(decrypted_buffer)

# Leer todas las hojas del archivo
xls = pd.ExcelFile(decrypted_buffer)
print(f"Hojas encontradas: {xls.sheet_names}")

# Leer cada hoja por separado
for sheet_name in xls.sheet_names:
    print(f"\n--- Hoja: {sheet_name} ---")
    
    # Leer la hoja completa para inspeccionar
    df_sheet = pd.read_excel(decrypted_buffer, sheet_name=sheet_name, header=None)
    
    # Mostrar primeras filas para entender estructura
    print("Primeras 10 filas:")
    for i in range(min(10, len(df_sheet))):
        print(f"Fila {i}: {df_sheet.iloc[i, :3].tolist()}")
    
    # Buscar el inicio de cada cuadro
    for i in range(len(df_sheet)):
        row = df_sheet.iloc[i, :2].astype(str).tolist()
        row_text = ' '.join([str(x) for x in row])
        if "Cuadro" in row_text and "Defunciones" in row_text:
            print(f"\n¡Cuadro encontrado en fila {i}!")
            print(f"Título: {row_text}")
            break

<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
C:\Users\juand\AppData\Local\Temp\ipykernel_28096\2024667367.py:7: SyntaxWarning: invalid escape sequence '\d'
  with open("data\dane\defunciones-no-fetales2022-cuadro-definitivo-2022.xls", "rb") as f:

Hojas encontradas: ['Indice', 'Listas', 'Cuadro1', 'Cuadro2', 'Cuadro3', 'Cuadro4', 'Cuadro5', 'Cuadro6', 'Cuadro7', 'Cuadro8', 'Cuadro9', 'Cuadro10', 'Cuadro11', 'Cuadro12', 'Cuadro13', 'Cuadro14', 'Cuadro15', 'Cuadro16']

--- Hoja: Indice ---
Primeras 10 filas:
Fila 0: [nan, nan]
Fila 1: [nan, nan]
Fila 2: ['Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: ['Defunciones no fetales año 2022', nan]
Fila 4: [nan, 'Total Nacional:      287.251']
Fila 5: [nan, 'Indice']
Fila 6: [nan, 'Seleccione …']
Fila 7: [nan, 'Cuadro 1    -  Defunciones por área donde ocurrió la defunción y sexo, según grupos de edad, total nacional']
Fila 8: [nan, 'Cuadro 2    -  Defunciones por persona que certifica la defunción, según departamento, área y sitio donde ocurrió la defunción']
Fila 9: [nan, 'Cuadro 3    -  Defunciones por grupos de edad y sexo, según departamento, municipio y área donde ocurrió la defunción']

¡Cuadro encontrado en fila 7!
Título: nan Cuadro 1    -  Defunciones por área donde ocurrió la defunción y sexo, según grupos de edad, total nacional

--- Hoja: Listas ---
Primeras 10 filas:
Fila 0: ['NOMDEP', 'CODDEP', np.float64(nan)]
Fila 1: ['Nacional', '03', np.float64(nan)]
Fila 2: ['Antioquia', '05', np.float64(nan)]
Fila 3: ['Atlántico', '08', np.float64(nan)]
Fila 4: ['Bogotá, D.C.', '11', np.float64(nan)]
Fila 5: ['Bolívar', '13', np.float64(nan)]
Fila 6: ['Boyacá', '15', np.float64(nan)]
Fila 7: ['Caldas', '17', np.float64(nan)]
Fila 8: ['Caquetá', '18', np.float64(nan)]
Fila 9: ['Cauca', '19', np.float64(nan)]

--- Hoja: Cuadro1 ---
Primeras 10 filas:
Fila 0: [nan, nan, nan]
Fila 1: [nan, nan, nan]
Fila 2: ['Estadísticas vitales de nacimientos y defunciones ', nan, nan]
Fila 3: ['CUADRO 1 - Defunciones por área donde ocurrió la defunción y sexo, según grupos de edad, total nacional', nan, nan]
Fila 4: ['Año 2022', nan, nan]
Fila 5: ['Volver al índice', nan, nan]
Fila 6: [nan, nan, nan]
Fila 7: ['GRUPOS DE EDAD', 'Total', 'Total']
Fila 8: [nan, nan, 'Hombres']
Fila 9: ['Total Nacional', 287251, 159171]

--- Hoja: Cuadro2 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 2 - Defunciones por persona que certifica la defunción, según departamento, área y sitio donde ocurrió la defunción', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', nan]
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento, área y sitio donde ocurrió la defunción', nan]
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'Total']

--- Hoja: Cuadro3 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), np.float64(nan), nan]
Fila 1: [np.float64(nan), np.float64(nan), nan]
Fila 2: [np.float64(nan), np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ']
Fila 3: [np.float64(nan), np.float64(nan), 'CUADRO 3 - Defunciones por grupos de edad y sexo, según departamento, municipio y área donde ocurrió la defunción']
Fila 4: [np.float64(nan), np.float64(nan), 'Año 2022']
Fila 5: [np.float64(nan), np.float64(nan), 'Volver al índice']
Fila 6: [np.float64(nan), np.float64(nan), nan]
Fila 7: [np.float64(nan), np.float64(nan), 'Departamento, municipio y área de ocurrencia']
Fila 8: [np.float64(nan), np.float64(nan), nan]
Fila 9: [np.float64(nan), np.float64(nan), nan]

--- Hoja: Cuadro4 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), np.float64(nan), nan]
Fila 1: [np.float64(nan), np.float64(nan), nan]
Fila 2: [np.float64(nan), np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ']
Fila 3: [np.float64(nan), np.float64(nan), 'CUADRO 4  -  Defunciones por grupos de edad y sexo, según departamento, municipio y área de residencia']
Fila 4: [np.float64(nan), np.float64(nan), 'Año 2022']
Fila 5: [np.float64(nan), np.float64(nan), 'Volver al índice']
Fila 6: [np.float64(nan), np.float64(nan), nan]
Fila 7: [np.float64(nan), np.float64(nan), 'Departamento, municipio y área de residencia']
Fila 8: [np.float64(nan), np.float64(nan), nan]
Fila 9: [np.float64(nan), np.float64(nan), nan]

--- Hoja: Cuadro5 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), np.float64(nan), nan]
Fila 1: [np.float64(nan), np.float64(nan), nan]
Fila 2: [np.float64(nan), np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ']
Fila 3: [np.float64(nan), np.float64(nan), 'CUADRO 5 - Defunciones por grupos de edad y sexo, según departamento, municipio de residencia y grupos de causas de defunción \n(Lista de causas agrupadas 6/67 CIE-10 de OPS)']
Fila 4: [np.float64(nan), np.float64(nan), 'Año 2022']
Fila 5: [np.float64(nan), np.float64(nan), 'Volver al índice']
Fila 6: [np.float64(nan), np.float64(nan), nan]
Fila 7: [np.float64(nan), np.float64(nan), 'Departamento y municipio de residencia | Grupos de causas de defunción\n(Lista de causas agrupadas 6/67 CIE-10 DE OPS)']
Fila 8: [np.float64(nan), np.float64(nan), nan]
Fila 9: [np.float64(3.0), np.float64(3000.0), 'Total Nacional']

--- Hoja: Cuadro6 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 6 - Defunciones por sitio donde ocurrió la defunción, según departamento de ocurrencia y régimen de seguridad social', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', nan]
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de ocurrencia y régimen de seguridad social del fallecido', nan]
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'TOTAL']

--- Hoja: Cuadro7 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 7 - Defunciones maternas, por grupos de edad, según departamento de residencia y grupos de causas de defunción \n(Lista de causas agrupadas 6/67 CIE-10 de OPS)', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', 'Departamento']
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de residencia | Grupos de causas de defunción \n(Lista de causas agrupadas 6/67 CIE-10 de OPS)', nan]
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'TOTAL']

--- Hoja: Cuadro8 ---
Primeras 10 filas:
Fila 0: [nan, nan, nan]
Fila 1: [nan, nan, nan]
Fila 2: ['Estadísticas vitales de nacimientos y defunciones ', nan, nan]
Fila 3: ['CUADRO 8 - Defunciones maternas por grupos de edad, según lista de causas a 3 caracteres CIE-10', nan, nan]
Fila 4: ['Año 2022', nan, nan]
Fila 5: ['Volver al índice', nan, nan]
Fila 6: [nan, nan, nan]
Fila 7: ['Lista de causas a 3 caracteres', 'Total', 'Grupos de edad']
Fila 8: [nan, nan, '10 - 14\n años']
Fila 9: ['Total Nacional', 464, 2]

--- Hoja: Cuadro9 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 9 - Defunciones por pertenencia étnico-racial del fallecido y sexo, según departamento de residencia', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', nan]
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de residencia', 'Total']
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 287251]

--- Hoja: Cuadro10 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 10 - Defunciones por probable manera de muerte y sexo, según departamento de ocurrencia', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', nan]
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de ocurrencia', 'Total']
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 287251]

--- Hoja: Cuadro11 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 11 - Defunciones por grupo de edad y sexo, según departamentos de ocurrencia y grupos de causas de defunción \n(Lista Colombia 105 para la tabulación de mortalidad)', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', 'Departamento']
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de ocurrencia | Grupos de causas de defunción (lista colombia 105 para la tabulación de mortalidad)', nan]
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'TOTAL']

--- Hoja: Cuadro12 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 12 - Defunciones por grupos de edad y sexo, según departamentos de residencia y grupos de causas de defunción \n(Lista Colombia 105 para la tabulación de mortalidad)', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', 'Departamento']
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de residencia | Grupos de causas de defunción (lista colombia 105 para la tabulación de mortalidad)', nan]
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'TOTAL']

--- Hoja: Cuadro13 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 13 - Defunciones de menores de un año por grupos de edad y sexo, según departamento de residencia de la madre y grupos de causas de defunción (Lista Colombia 105 para la tabulación de mortalidad)', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', 'Departamento']
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Grupos de causas de defunción (lista Colombia 105 para la tabulación de mortalidad)', nan]
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'TOTAL']

--- Hoja: Cuadro14 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 14 - Defunciones de menores de un año por grupos de edad y sexo, según departamento de residencia y grupo de edad de la madre', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', nan]
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de residencia y grupo de edad de la madre', nan]
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'TOTAL']

--- Hoja: Cuadro15 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), np.float64(nan), nan]
Fila 1: [np.float64(nan), np.float64(nan), nan]
Fila 2: [np.float64(nan), np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ']
Fila 3: [np.float64(nan), np.float64(nan), 'CUADRO 15 - Defunciones por grupos de edad y sexo, según departamento, municipio de ocurrencia y grupos de causas externas \n(Lista de causas agrupadas 6/67 cie-10 de OPS)']
Fila 4: [np.float64(nan), np.float64(nan), 'Año 2022']
Fila 5: [np.float64(nan), np.float64(nan), 'Volver al índice']
Fila 6: [np.float64(nan), np.float64(nan), nan]
Fila 7: [np.float64(nan), np.float64(nan), 'Departamento y municipio de ocurrencia | LISTA 6/67 CIE 10 DE OPS']
Fila 8: [np.float64(nan), np.float64(nan), nan]
Fila 9: [np.float64(3.0), np.float64(3000.0), 'Total Nacional']

--- Hoja: Cuadro16 ---
Primeras 10 filas:
Fila 0: [np.float64(nan), nan, nan]
Fila 1: [np.float64(nan), nan, nan]
Fila 2: [np.float64(nan), 'Estadísticas vitales de nacimientos y defunciones ', nan]
Fila 3: [np.float64(nan), 'CUADRO 16 - Diez primeras causas de defunción, según departamento de residencia', nan]
Fila 4: [np.float64(nan), 'Año 2022', nan]
Fila 5: [np.float64(nan), 'Volver al índice', 'Departamento']
Fila 6: [np.float64(nan), nan, nan]
Fila 7: [np.float64(nan), 'Departamento de Residencia', 'Causas de defunción a 3 caracteres CIE-10']
Fila 8: [np.float64(nan), nan, nan]
Fila 9: [np.float64(3.0), 'Total Nacional', 'Total Defunciones']

In [65]:
import msoffcrypto
import io
import pandas as pd
import numpy as np
import os

# Desencriptar el archivo
decrypted_buffer = io.BytesIO()
with open("data\dane\anex-EEVV-DefuncionesNoFetalesCuadroAnoCorrido-2025pr.xlsx", "rb") as f:
    office_file = msoffcrypto.OfficeFile(f)
    office_file.load_key(password="VelvetSweatshop")
    office_file.decrypt(decrypted_buffer)

# Leer todas las hojas del archivo
xls = pd.ExcelFile(decrypted_buffer)
print(f"Hojas encontradas: {xls.sheet_names}")

# Crear carpeta para guardar los datasets si no existe
if not os.path.exists('datasets_defunciones'):
    os.makedirs('datasets_defunciones')
    print("\n📁 Carpeta 'datasets_defunciones' creada")

# Diccionario para guardar todos los dataframes
dataframes = {}

# Función para limpiar nombres de columnas
def limpiar_nombre_columna(nombre):
    if pd.isna(nombre) or nombre == '' or nombre == 'nan':
        return 'columna'
    return str(nombre).strip().replace('\n', ' ').replace('  ', ' ')

# Procesar cada hoja
for sheet_name in xls.sheet_names:
    print(f"\n{'='*60}")
    print(f"PROCESANDO HOJA: {sheet_name}")
    print('='*60)
    
    # Leer la hoja completa
    df_sheet = pd.read_excel(decrypted_buffer, sheet_name=sheet_name, header=None)
    
    # Mostrar estructura
    print(f"\n📊 Dimensiones de la hoja: {df_sheet.shape}")
    print("Primeras 5 filas (vista previa):")
    for i in range(min(5, len(df_sheet))):
        print(f"  Fila {i}: {df_sheet.iloc[i, :3].tolist()}")
    
    # BUSCAR LA ESTRUCTURA DE CADA HOJA
    print("\n🔍 Analizando estructura...")
    
    # Encontrar dónde empiezan los datos reales
    fila_inicio_datos = None
    fila_encabezados = None
    
    for i in range(len(df_sheet)):
        fila = df_sheet.iloc[i].fillna('').astype(str)
        
        # Buscar patrones que indican inicio de datos
        texto_fila = ' '.join(fila[:5].tolist()).upper()
        
        if any(patron in texto_fila for patron in ['TOTAL NACIONAL', 'DEPARTAMENTO', 'GRUPOS DE EDAD', 'TOTAL', 'HOMBRES', 'MUJERES']):
            # Esta fila podría ser encabezado o datos
            if i > 0:
                # Verificar si la fila anterior tiene títulos
                fila_anterior = df_sheet.iloc[i-1].fillna('').astype(str)
                texto_anterior = ' '.join(fila_anterior[:5].tolist())
                
                if 'CUADRO' in texto_anterior.upper():
                    # La fila actual son los encabezados
                    fila_encabezados = i
                    fila_inicio_datos = i + 1
                    print(f"  ✅ Encabezados encontrados en fila {i}")
                    print(f"  ✅ Datos comienzan en fila {i+1}")
                    break
                else:
                    # La fila actual podría ser tanto encabezados como datos
                    fila_encabezados = i
                    fila_inicio_datos = i + 1
                    print(f"  ⚠️ Posibles encabezados en fila {i}")
                    break
    
    # Si no se encontró estructura, buscar por 'Cuadro'
    if fila_inicio_datos is None:
        for i in range(len(df_sheet)):
            fila = df_sheet.iloc[i, :2].astype(str).tolist()
            texto = ' '.join([str(x) for x in fila])
            if "Cuadro" in texto and "Defunciones" in texto:
                # El cuadro comienza aquí, los datos están 3-4 filas después
                fila_inicio_datos = i + 3
                fila_encabezados = i + 2
                print(f"  ✅ Cuadro encontrado en fila {i}")
                print(f"  ✅ Datos desde fila {fila_inicio_datos}")
                break
    
    # Extraer los datos
    if fila_inicio_datos is not None and fila_inicio_datos < len(df_sheet):
        try:
            # Obtener encabezados
            if fila_encabezados is not None and fila_encabezados < len(df_sheet):
                encabezados_raw = df_sheet.iloc[fila_encabezados].fillna('').tolist()
            else:
                encabezados_raw = df_sheet.iloc[fila_inicio_datos - 1].fillna('').tolist()
            
            # Limpiar encabezados
            encabezados = [limpiar_nombre_columna(h) for h in encabezados_raw]
            
            # Crear diccionario para evitar columnas duplicadas
            encabezados_unicos = []
            contadores = {}
            
            for h in encabezados:
                if h in contadores:
                    contadores[h] += 1
                    encabezados_unicos.append(f"{h}_{contadores[h]}")
                else:
                    contadores[h] = 0
                    encabezados_unicos.append(h)
            
            # Extraer datos
            datos = df_sheet.iloc[fila_inicio_datos:].copy()
            datos.columns = encabezados_unicos
            
            # Limpiar datos
            # Eliminar filas totalmente vacías
            datos = datos.dropna(how='all')
            
            # Eliminar columnas totalmente vacías
            datos = datos.dropna(axis=1, how='all')
            
            # Eliminar filas que son solo títulos o notas
            datos = datos[~datos.iloc[:, 0].astype(str).str.contains('Volver al índice|Cuadro|Fuente|Notas', na=False)]
            
            # Resetear índice
            datos = datos.reset_index(drop=True)
            
            # Guardar en el diccionario
            nombre_dataset = f"defunciones_{sheet_name.lower()}"
            dataframes[nombre_dataset] = datos
            
            print(f"\n📦 DATASET CREADO: {nombre_dataset}")
            print(f"   • Filas: {len(datos)}")
            print(f"   • Columnas: {len(datos.columns)}")
            print(f"   • Columnas: {datos.columns.tolist()}")
            
            # Mostrar muestra
            print("\n   Muestra de datos (primeras 3 filas):")
            print(datos.head(3).to_string())
            
            # Guardar a CSV
            archivo_csv = f"datasets_defunciones/{nombre_dataset}.csv"
            datos.to_csv(archivo_csv, index=False, encoding='utf-8-sig')
            print(f"   💾 Guardado en: {archivo_csv}")
            
        except Exception as e:
            print(f"❌ Error al procesar {sheet_name}: {e}")
            print("   Continuando con la siguiente hoja...")
    else:
        print(f"⚠️ No se pudo determinar la estructura de datos para {sheet_name}")

# RESUMEN FINAL
print("\n" + "="*60)
print("RESUMEN FINAL - DATASETS CREADOS")
print("="*60)

total_filas = 0
for nombre, df in dataframes.items():
    print(f"\n📊 {nombre}:")
    print(f"   • Filas: {len(df):,}")
    print(f"   • Columnas: {len(df.columns)}")
    print(f"   • Archivo: datasets_defunciones/{nombre}.csv")
    total_filas += len(df)

print(f"\n✅ TOTAL: {len(dataframes)} datasets creados")
print(f"✅ TOTAL DE FILAS COMBINADAS: {total_filas:,}")
print(f"📁 Los archivos están en la carpeta 'datasets_defunciones/'")

# Mostrar todos los datasets disponibles
print("\n📋 DATASETS DISPONIBLES:")
for i, nombre in enumerate(dataframes.keys(), 1):
    print(f"  {i}. {nombre}")

<>:9: SyntaxWarning: invalid escape sequence '\d'
<>:9: SyntaxWarning: invalid escape sequence '\d'
C:\Users\juand\AppData\Local\Temp\ipykernel_28096\3244725043.py:9: SyntaxWarning: invalid escape sequence '\d'
  with open("data\dane\anex-EEVV-DefuncionesNoFetalesCuadroAnoCorrido-2025pr.xlsx", "rb") as f:
C:\Users\juand\AppData\Local\Temp\ipykernel_28096\3244725043.py:9: SyntaxWarning: invalid escape sequence '\d'
  with open("data\dane\anex-EEVV-DefuncionesNoFetalesCuadroAnoCorrido-2025pr.xlsx", "rb") as f:

OSError: [Errno 22] Invalid argument: 'data\\dane\x07nex-EEVV-DefuncionesNoFetalesCuadroAnoCorrido-2025pr.xlsx'

In [63]:
# Después de ejecutar el código anterior, puedes explorar cada dataset

print("\n" + "="*60)
print("EXPLORACIÓN DE DATASETS")
print("="*60)

# Función para explorar un dataset específico
def explorar_dataset(nombre_dataset):
    if nombre_dataset in dataframes:
        df = dataframes[nombre_dataset]
        print(f"\n📊 EXPLORANDO: {nombre_dataset}")
        print(f"Dimensiones: {df.shape}")
        print("\nPrimeras 5 filas:")
        print(df.head())
        print("\nInformación de columnas:")
        print(df.info())
        print("\nEstadísticas básicas:")
        print(df.describe())
        return df
    else:
        print(f"Dataset '{nombre_dataset}' no encontrado")
        return None

# Ejemplo: explorar el primer dataset
if dataframes:
    primer_dataset = list(dataframes.keys())[0]
    explorar_dataset(primer_dataset)

# Ver todos los datasets y sus primeras filas
print("\n" + "="*60)
print("VISTA PREVIA DE TODOS LOS DATASETS")
print("="*60)

for nombre, df in dataframes.items():
    print(f"\n📁 {nombre} ({len(df)} filas, {len(df.columns)} columnas)")
    print(df.head(3).to_string())
    print("-" * 40)

============================================================
EXPLORACIÓN DE DATASETS
============================================================

📊 EXPLORANDO: defunciones_indice
Dimensiones: (21, 2)

Primeras 5 filas:
  columna                          Total Nacional:   287.251
0     NaN                                             Indice
1     NaN                                       Seleccione …
2     NaN  Cuadro 1    -  Defunciones por área donde ocur...
3     NaN  Cuadro 2    -  Defunciones por persona que cer...
4     NaN  Cuadro 3    -  Defunciones por grupos de edad ...

Información de columnas:
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   columna                    3 non-null      str
 1   Total Nacional:   287.251  18 non-null     str
dtypes: str(2)
memory usage: 468.0 bytes
None

Estadísticas básicas:
                     columna Total Nacional:   287.251
count                      3                        18
unique                     3                        18
top     De menores de un año                    Indice
freq                       1                         1

============================================================
VISTA PREVIA DE TODOS LOS DATASETS
============================================================

📁 defunciones_indice (21 filas, 2 columnas)
  columna                                                                                    Total Nacional:   287.251
0     NaN                                                                                                       Indice
1     NaN                                                                                                 Seleccione …
2     NaN  Cuadro 1    -  Defunciones por área donde ocurrió la defunción y sexo, según grupos de edad, total nacional
----------------------------------------

📁 defunciones_cuadro1 (35 filas, 17 columnas)
  CUADRO 1 - Defunciones por área donde ocurrió la defunción y sexo, según grupos de edad, total nacional columna columna_1 columna_2      columna_3           columna_4 columna_5      columna_6       columna_7 columna_8      columna_9      columna_10 columna_11     columna_12       columna_13 columna_14     columna_15
0                                                                                                Año 2022     NaN       NaN       NaN            NaN                 NaN       NaN            NaN             NaN       NaN            NaN             NaN        NaN            NaN              NaN        NaN            NaN
1                                                                                          GRUPOS DE EDAD   Total     Total       NaN            NaN  Cabecera municipal       NaN            NaN  Centro poblado       NaN            NaN  Rural disperso        NaN            NaN  Sin información        NaN            NaN
2                                                                                                     NaN     NaN   Hombres   Mujeres  Indeterminado             Hombres   Mujeres  Indeterminado         Hombres   Mujeres  Indeterminado         Hombres    Mujeres  Indeterminado          Hombres    Mujeres  Indeterminado
----------------------------------------

📁 defunciones_cuadro2 (1366 filas, 11 columnas)
   columna CUADRO 2 - Defunciones por persona que certifica la defunción, según departamento, área y sitio donde ocurrió la defunción columna_1 columna_2 columna_3                              columna_4 columna_5 columna_6 columna_7 columna_8 columna_9
0      NaN                                                                                                                   Año 2022       NaN       NaN       NaN                                    NaN       NaN       NaN       NaN       NaN       NaN
1      NaN                                                                                                           Volver al índice       NaN       NaN       NaN                           Departamento       NaN       NaN       NaN       NaN       NaN
2      NaN                                                                      Departamento, área y sitio donde ocurrió la defunción       NaN       NaN     Total  Certificado de defunción expedido por       NaN       NaN       NaN       NaN       NaN
----------------------------------------

📁 defunciones_cuadro3 (5947 filas, 36 columnas)
   columna  columna_1 CUADRO 3 - Defunciones por grupos de edad y sexo, según departamento, municipio y área donde ocurrió la defunción columna_2     columna_3 columna_4 columna_5 columna_6  columna_7      columna_8 columna_9 columna_10 columna_11 columna_12 columna_13 columna_14 columna_15 columna_16 columna_17 columna_18 columna_19 columna_20 columna_21 columna_22 columna_23 columna_24 columna_25 columna_26 columna_27 columna_28 columna_29 columna_30 columna_31 columna_32 columna_33 columna_34
0      NaN        NaN                                                                                                          Año 2022       NaN           NaN       NaN       NaN       NaN        NaN            NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
1      NaN        NaN                                                                                                  Volver al índice       NaN  Departamento       NaN       NaN       NaN  Municipio            NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2      NaN        NaN                                                                      Departamento, municipio y área de ocurrencia       NaN           NaN     Total     Total       NaN        NaN  Grupo de edad       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
----------------------------------------

📁 defunciones_cuadro4 (5989 filas, 99 columnas)
   columna  columna_1 CUADRO 4 - Defunciones por grupos de edad y sexo, según departamento, municipio y área de residencia columna_2     columna_3 columna_4 columna_5 columna_6  columna_7       columna_8 columna_9 columna_10 columna_11 columna_12 columna_13 columna_14 columna_15 columna_16 columna_17 columna_18 columna_19 columna_20 columna_21 columna_22 columna_23 columna_24 columna_25 columna_26 columna_27 columna_28 columna_29 columna_30 columna_31 columna_32 columna_33 columna_34 columna_35 columna_36 columna_37 columna_38 columna_39 columna_40 columna_41 columna_42 columna_43 columna_44 columna_45 columna_46 columna_47 columna_48 columna_49 columna_50 columna_51 columna_52 columna_53 columna_54 columna_55 columna_56 columna_57 columna_58 columna_59 columna_60 columna_61 columna_62 columna_63 columna_64 columna_65 columna_66 columna_67 columna_68 columna_69 columna_70 columna_71 columna_72 columna_73 columna_74 columna_75 columna_76 columna_77 columna_78 columna_79 columna_80 columna_81 columna_82 columna_83 columna_84 columna_85 columna_86 columna_87 columna_88 columna_89 columna_90 columna_91 columna_92 columna_93 columna_94 columna_95 columna_96 columna_97
0      NaN        NaN                                                                                             Año 2022       NaN           NaN       NaN       NaN       NaN        NaN             NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
1      NaN        NaN                                                                                     Volver al índice       NaN  Departamento       NaN       NaN       NaN  Municipio             NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2      NaN        NaN                                                         Departamento, municipio y área de residencia       NaN           NaN     Total     Total       NaN        NaN  Grupos de edad       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
----------------------------------------

📁 defunciones_cuadro5 (35014 filas, 36 columnas)
   columna  columna_1 CUADRO 5 - Defunciones por grupos de edad y sexo, según departamento, municipio de residencia y grupos de causas de defunción (Lista de causas agrupadas 6/67 CIE-10 de OPS) columna_2     columna_3  columna_4 columna_5 columna_6 columna_7    columna_8 columna_9 columna_10   columna_11 columna_12 columna_13    columna_14 columna_15 columna_16     columna_17 columna_18 columna_19     columna_20 columna_21 columna_22     columna_23 columna_24 columna_25     columna_26 columna_27 columna_28    columna_29 columna_30 columna_31        columna_32 columna_33 columna_34
0      NaN        NaN                                                                                                                                                                     Año 2022       NaN           NaN        NaN       NaN       NaN       NaN          NaN       NaN        NaN          NaN        NaN        NaN           NaN        NaN        NaN            NaN        NaN        NaN            NaN        NaN        NaN            NaN        NaN        NaN            NaN        NaN        NaN           NaN        NaN        NaN               NaN        NaN        NaN
1      NaN        NaN                                                                                                                                                             Volver al índice       NaN  Departamento  Municipio       NaN       NaN       NaN          NaN       NaN        NaN          NaN        NaN        NaN           NaN        NaN        NaN            NaN        NaN        NaN            NaN        NaN        NaN            NaN        NaN        NaN            NaN        NaN        NaN           NaN        NaN        NaN               NaN        NaN        NaN
2      NaN        NaN                                                       Departamento y municipio de residencia | Grupos de causas de defunción\n(Lista de causas agrupadas 6/67 CIE-10 DE OPS)       NaN           NaN      Total     Total       NaN       NaN  Menor 1 año       NaN        NaN  De 1-4 años        NaN        NaN  De 5-14 años        NaN        NaN  De 15-44 años        NaN        NaN  De 45-64 años        NaN        NaN  De 65-84 años        NaN        NaN  De 85-99 años        NaN        NaN  De 100 y más        NaN        NaN  Edad desconocida        NaN        NaN
----------------------------------------

📁 defunciones_cuadro6 (244 filas, 11 columnas)
   columna CUADRO 6 - Defunciones por sitio donde ocurrió la defunción, según departamento de ocurrencia y régimen de seguridad social columna_1 columna_2                         columna_3     columna_4 columna_5 columna_6 columna_7 columna_8 columna_9
0      NaN                                                                                                                    Año 2022       NaN       NaN                               NaN           NaN       NaN       NaN       NaN       NaN       NaN
1      NaN                                                                                                            Volver al índice       NaN       NaN                               NaN  Departamento       NaN       NaN       NaN       NaN       NaN
2      NaN                                                      Departamento de ocurrencia y régimen de seguridad social del fallecido       NaN     Total  Sitio donde ocurrió la defunción           NaN       NaN       NaN       NaN       NaN       NaN
----------------------------------------

📁 defunciones_cuadro7 (278 filas, 14 columnas)
   columna CUADRO 7 - Defunciones maternas, por grupos de edad, según departamento de residencia y grupos de causas de defunción (Lista de causas agrupadas 6/67 CIE-10 de OPS)     columna_1 columna_2       columna_3 columna_4 columna_5 columna_6 columna_7 columna_8 columna_9 columna_10 columna_11 columna_12
0      NaN                                                                                                                                                             Año 2022           NaN       NaN             NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN        NaN        NaN
1      NaN                                                                                                                                                     Volver al índice  Departamento       NaN             NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN        NaN        NaN
2      NaN                                                          Departamento de residencia | Grupos de causas de defunción \n(Lista de causas agrupadas 6/67 CIE-10 de OPS)           NaN     Total  Grupos de edad       NaN       NaN       NaN       NaN       NaN       NaN        NaN        NaN        NaN
----------------------------------------

📁 defunciones_cuadro8 (44 filas, 12 columnas)
  CUADRO 8 - Defunciones maternas por grupos de edad, según lista de causas a 3 caracteres CIE-10 columna       columna_1       columna_2       columna_3       columna_4       columna_5       columna_6       columna_7       columna_8       columna_9        columna_10
0                                                                                        Año 2022     NaN             NaN             NaN             NaN             NaN             NaN             NaN             NaN             NaN             NaN               NaN
1                                                                  Lista de causas a 3 caracteres   Total  Grupos de edad             NaN             NaN             NaN             NaN             NaN             NaN             NaN             NaN               NaN
2                                                                                             NaN     NaN  10 - 14\n años  15 - 19\n años  20 - 24\n años  25 - 29\n años  30 - 34\n años  35 - 39\n años  40 - 44\n años  45 - 49\n años  50 - 54\n años  Edad desconocida
----------------------------------------

📁 defunciones_cuadro9 (42 filas, 27 columnas)
   columna CUADRO 9 - Defunciones por pertenencia étnico-racial del fallecido y sexo, según departamento de residencia columna_1 columna_2     columna_3 columna_4 columna_5 columna_6 columna_7     columna_8 columna_9 columna_10                                           columna_11 columna_12 columna_13                 columna_14 columna_15 columna_16                                                 columna_17 columna_18 columna_19                 columna_20 columna_21 columna_22       columna_23 columna_24 columna_25
0      NaN                                                                                                    Año 2022       NaN       NaN           NaN       NaN       NaN       NaN       NaN           NaN       NaN        NaN                                                  NaN        NaN        NaN                        NaN        NaN        NaN                                                        NaN        NaN        NaN                        NaN        NaN        NaN              NaN        NaN        NaN
1      NaN                                                                                            Volver al índice       NaN       NaN  Departamento       NaN       NaN       NaN       NaN           NaN       NaN        NaN                                                  NaN        NaN        NaN                        NaN        NaN        NaN                                                        NaN        NaN        NaN                        NaN        NaN        NaN              NaN        NaN        NaN
2      NaN                                                                                  Departamento de residencia     Total     Total           NaN       NaN  Indígena       NaN       NaN  Rom (Gitano)       NaN        NaN  Raizal del archipielago de San Andres y Providencia        NaN        NaN  Palenquero de San Basilio        NaN        NaN  Negro(a), mulato(a), afrocolombiano(a) o afrodescendiente        NaN        NaN  Ninguno de las anteriores        NaN        NaN  Sin información        NaN        NaN
----------------------------------------

📁 defunciones_cuadro10 (40 filas, 16 columnas)
   columna CUADRO 10 - Defunciones por probable manera de muerte y sexo, según departamento de ocurrencia columna_1 columna_2 columna_3     columna_4 columna_5 columna_6 columna_7   columna_8 columna_9 columna_10  columna_11 columna_12 columna_13  columna_25

In [66]:
import pandas as pd
import os
from pathlib import Path

carpeta_base = 'datasets_defunciones_completos'

# Función para inspeccionar un cuadro específico de todos los años
def inspeccionar_cuadro(nombre_cuadro):
    """
    Inspecciona un cuadro específico (ej: 'cuadro1', 'cuadro5', etc.) en todos los años
    """
    print(f"\n{'='*70}")
    print(f"INSPECCIONANDO: {nombre_cuadro.upper()} - TODOS LOS AÑOS")
    print('='*70)
    
    for año in ['2022', '2023', '2024', '2025']:
        carpeta_año = os.path.join(carpeta_base, f'año_{año}')
        if not os.path.exists(carpeta_año):
            continue
            
        # Buscar archivos que coincidan con el cuadro
        archivos = [f for f in os.listdir(carpeta_año) 
                   if f.endswith('.csv') and nombre_cuadro.lower() in f.lower()]
        
        for archivo in archivos:
            ruta = os.path.join(carpeta_año, archivo)
            df = pd.read_csv(ruta)
            
            print(f"\n📁 AÑO {año} - {archivo}")
            print(f"   • Filas: {len(df):,}")
            print(f"   • Columnas: {len(df.columns)}")
            print(f"   • Columnas: {df.columns.tolist()[:10]}...")  # Primeras 10 columnas
            print(f"   • Tipos de datos:\n{df.dtypes.value_counts()}")
            print(f"\n   Primeras 3 filas:")
            print(df.head(3).to_string())
            print("-" * 40)

# Inspeccionar Cuadro 1 (defunciones por área y sexo)
inspeccionar_cuadro('cuadro1')

# Inspeccionar Cuadro 5 (defunciones por depto y causas)
inspeccionar_cuadro('cuadro5')

# Inspeccionar Cuadro 11 (el más grande)
inspeccionar_cuadro('cuadro11')

======================================================================
INSPECCIONANDO: CUADRO1 - TODOS LOS AÑOS
======================================================================

📁 AÑO 2022 - defunciones_2022_cuadro1.csv
   • Filas: 32
   • Columnas: 19
   • Columnas: ['columna', 'columna_1', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1', 'Mujeres_1', 'Indeterminado_1', 'Hombres_2', 'Mujeres_2']...
   • Tipos de datos:
float64    16
str         2
int64       1
Name: count, dtype: int64

   Primeras 3 filas:
           columna  columna_1   Hombres   Mujeres  Indeterminado  Hombres_1  Mujeres_1  Indeterminado_1  Hombres_2  Mujeres_2  Indeterminado_2  Hombres_3  Mujeres_3  Indeterminado_3  Hombres_4  Mujeres_4  Indeterminado_4   año hoja_origen
0   Total Nacional   287251.0  159171.0  128030.0           50.0   139563.0   118160.0             28.0     4524.0     2642.0              0.0    14240.0     6775.0             14.0      844.0      453.0              8.0  2022     Cuadro1
1     Menor 1 hora      312.0     173.0     137.0            2.0      167.0      132.0              2.0        0.0        0.0              0.0        6.0        5.0              0.0        0.0        0.0              0.0  2022     Cuadro1
2  De 1 a 23 horas      774.0     418.0     355.0            1.0      405.0      348.0              1.0        4.0        0.0              0.0        8.0        7.0              0.0        1.0        0.0              0.0  2022     Cuadro1
----------------------------------------

📁 AÑO 2022 - defunciones_2022_cuadro10.csv
   • Filas: 36
   • Columnas: 18
   • Columnas: ['columna', 'columna_1', 'columna_2', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1', 'Mujeres_1', 'Indeterminado_1', 'Hombres_2']...
   • Tipos de datos:
float64    15
str         2
int64       1
Name: count, dtype: int64

   Primeras 3 filas:
   columna       columna_1  columna_2   Hombres   Mujeres  Indeterminado  Hombres_1  Mujeres_1  Indeterminado_1  Hombres_2  Mujeres_2  Indeterminado_2  Hombres_3  Mujeres_3  Indeterminado_3  columna_14   año hoja_origen
0      3.0  Total Nacional   287251.0  159171.0  128030.0           50.0   129278.0   122084.0              6.0    28961.0     5555.0             25.0      932.0      391.0             19.0         NaN  2022    Cuadro10
1      5.0    05 Antioquia    40914.0   22323.0   18588.0            3.0    17911.0    17718.0              1.0     4232.0      790.0              2.0      180.0       80.0              0.0         NaN  2022    Cuadro10
2      8.0    08 Atlántico    16532.0    8881.0    7650.0            1.0     7592.0     7407.0              0.0     1274.0      232.0              0.0       15.0       11.0              1.0         NaN  2022    Cuadro10
----------------------------------------

📁 AÑO 2022 - defunciones_2022_cuadro11.csv
   • Filas: 3,153
   • Columnas: 99
   • Columnas: ['columna', 'columna_1', 'columna_2', 'columna_3', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1', 'Mujeres_1', 'Indeterminado_1']...
   • Tipos de datos:
float64    95
str         3
int64       1
Name: count, dtype: int64

   Primeras 3 filas:
   columna       columna_1                                  columna_2  columna_3   Hombres   Mujeres  Indeterminado  Hombres_1  Mujeres_1  Indeterminado_1  Hombres_2  Mujeres_2  Indeterminado_2  Hombres_3  Mujeres_3  Indeterminado_3  Hombres_4  Mujeres_4  Indeterminado_4  Hombres_5  Mujeres_5  Indeterminado_5  Hombres_6  Mujeres_6  Indeterminado_6  Hombres_7  Mujeres_7  Indeterminado_7  Hombres_8  Mujeres_8  Indeterminado_8  Hombres_9  Mujeres_9  Indeterminado_9  Hombres_10  Mujeres_10  Indeterminado_10  Hombres_11  Mujeres_11  Indeterminado_11  Hombres_12  Mujeres_12  Indeterminado_12  Hombres_13  Mujeres_13  Indeterminado_13  Hombres_14  Mujeres_14  Indeterminado_14  Hombres_15  Mujeres_15  Indeterminado_15  Hombres_16  Mujeres_16  Indeterminado_16  Hombres_17  Mujeres_17  Indeterminado_17  Hombres_18  Mujeres_18  Indeterminado_18  Hombres_19  Mujeres_19  Indeterminado_19  Hombres_20  Mujeres_20  Indeterminado_20  Hombres_21  Mujeres_21  Indeterminado_21  Hombres_22  Mujeres_22  Indeterminado_22  Hombres_23  Mujeres_23  Indeterminado_23  Hombres_24  Mujeres_24  Indeterminado_24  Hombres_25  Mujeres_25  Indeterminado_25  Hombres_26  Mujeres_26  Indeterminado_26  Hombres_27  Mujeres_27  Indeterminado_27  Hombres_28  Mujeres_28  Indeterminado_28  Hombres_29  Mujeres_29  Indeterminado_29  Hombres_30  Mujeres_30  Indeterminado_30   año hoja_origen
0      3.0  Total Nacional                                      TOTAL   287251.0  159171.0  128030.0           50.0      173.0      137.0              2.0      418.0      355.0              1.0      958.0      719.0              2.0      772.0      639.0              1.0       36.0       18.0              0.0      944.0      761.0              1.0      434.0      318.0              0.0      396.0      325.0              0.0      536.0      414.0              0.0       472.0       364.0               0.0       713.0       499.0               0.0      2820.0       872.0               0.0      5277.0      1206.0               1.0      5512.0      1333.0               1.0      5008.0      1564.0               2.0      4534.0      1914.0               2.0      4634.0      2495.0               3.0      4607.0      3005.0               0.0      5812.0      4132.0               1.0      8232.0      5832.0               0.0     11076.0      7693.0               5.0     13603.0      9661.0               0.0     15942.0     11609.0               2.0     17092.0     13633.0               1.0     18618.0     17408.0               6.0     15656.0     18500.0               1.0     10343.0     14397.0               2.0      3716.0      6403.0               0.0       824.0      1822.0               3.0        13.0         2.0              13.0  2022    Cuadro11
1      3.0             NaN  001 Enfermedades infecciosas intestinales     1170.0     519.0     651.0            0.0        0.0        0.0              0.0        0.0        0.0              0.0        3.0        5.0              0.0        9.0        9.0              0.0        0.0        0.0              0.0       32.0       26.0              0.0       21.0       22.0              0.0       19.0       10.0              0.0       10.0        9.0              0.0        11.0         3.0               0.0         9.0         3.0               0.0         6.0         3.0               0.0         6.0         1.0               0.0         5.0         4.0               0.0         8.0         4.0               0.0         9.0         0.0               0.0        14.0         7.0               0.0         8.0         7.0               0.0        15.0        12.0               0.0        19.0        30.0               0.0        26.0        37.0               0.0        30.0        46.0               0.0        45.0        48.0               0.0        54.0        72.0               0.0        45.0       106.0               0.0        59.0        78.0               0.0        42.0        79.0               0.0        14.0        21.0               0.0         0.0         9.0               0.0         0.0         0.0               0.0  2022    Cuadro11
2      3.0             NaN                002 Tuberculosis y secuelas     1402.0    1007.0     395.0            0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        3.0        1.0              0.0        1.0        0.0              0.0        1.0        3.0              0.0        5.0        3.0              0.0         1.0         0.0               0.0         2.0         3.0               0.0        13.0        12.0               0.0        39.0        18.0               0.0        50.0        13.0               0.0        50.0        23.0               0.0        55.0        14.0               0.0        52.0        17.0               0.0        46.0        16.0               0.0        57.0        18.0               0.0        74.0        34.0               0.0       114.0        35.0               0.0       118.0        36.0               0.0       105.0        43.0               0.0        79.0        34.0               0.0        81.0        35.0               0.0        40.0        30.0               0.0        18.0         2.0               0.0         3.0         5.0               0.0         0.0         0.0               0.0         0.0         0.0               0.0  2022    Cuadro11
----------------------------------------

📁 AÑO 2022 - defunciones_2022_cuadro12.csv
   • Filas: 3,818
   • Columnas: 99
   • Columnas: ['columna', 'columna_1', 'columna_2', 'columna_3', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1', 'Mujeres_1', 'Indeterminado_1']...
   • Tipos de datos:
float64    95
str         3
int64       1
Name: count, dtype: int64

   Primeras 3 filas:
   columna       columna_1                                  columna_2  columna_3   Hombres   Mujeres  Indeterminado  Hombres_1  Mujeres_1  Indeterminado_1  Hombres_2  Mujeres_2  Indeterminado_2  Hombres_3  Mujeres_3  Indeterminado_3  Hombres_4  Mujeres_4  Indeterminado_4  Hombres_5  Mujeres_5  Indeterminado_5  Hombres_6  Mujeres_6  Indeterminado_6  Hombres_7  Mujeres_7  Indeterminado_7  Hombres_8  Mujeres_8  Indeterminado_8  Hombres_9  Mujeres_9  Indeterminado_9  Hombres_10  Mujeres_10  Indeterminado_10  Hombres_11  Mujeres_11  Indeterminado_11  Hombres_12  Mujeres_12  Indeterminado_12  Hombres_13  Mujeres_13  Indeterminado_13  Hombres_14  Mujeres_14  Indeterminado_14  Hombres_15  Mujeres_15  Indeterminado_15  Hombres_16  Mujeres_16  Indeterminado_16  Hombres_17  Mujeres_17  Indeterminado_17  Hombres_18  Mujeres_18  Indeterminado_18  Hombres_19  Mujeres_19  Indeterminado_19  Hombres_20  Mujeres_20  Indeterminado_20  Hombres_21  Mujeres_21  Indeterminado_21  Hombres_22  Mujeres_22  Indeterminado_22  Hombres_23  Mujeres_23  Indeterminado_23  Hombres_24  Mujeres_24  Indeterminado_24  Hombres_25  Mujeres_25  Indeterminado_25  Hombres_26  Mujeres_26  Indeterminado_26  Hombres_27  Mujeres_27  Indeterminado_27  Hombres_28  Mujeres_28  Indeterminado_28  Hombres_29  Mujeres_29  Indeterminado_29  Hombres_30  Mujeres_30  Indeterminado_30   año hoja_origen
0      3.0  Total Nacional                                      TOTAL   287251.0  159171.0  128030.0           50.0      173.0      137.0              2.0      418.0      355.0              1.0      958.0      719.0              2.0      772.0      639.0              1.0       36.0       18.0              0.0      944.0      761.0              1.0      434.0      318.0              0.0      396.0      325.0              0.0      536.0      414.0              0.0       472.0       364.0               0.0       713.0       499.0               0.0      2820.0       872.0               0.0      5277.0      1206.0               1.0      5512.0      1333.0               1.0      5008.0      1564.0               2.0      4534.0      1914.0               2.0      4634.0      2495.0               3.0      4607.0      3005.0               0.0      5812.0      4132.0               1.0      8232.0      5832.0               0.0     11076.0      7693.0               5.0     13603.0      9661.0               0.0     15942.0     11609.0               2.0     17092.0     13633.0               1.0     18618.0     17408.0               6.0     15656.0     18500.0               1.0     10343.0     14397.0               2.0      3716.0      6403.0               0.0       824.0      1822.0               3.0        13.0         2.0              13.0  2022    Cuadro12
1      3.0             NaN  001 Enfermedades infecciosas intestinales     1170.0     519.0     651.0            0.0        0.0        0.0              0.0        0.0        0.0              0.0        3.0        5.0              0.0        9.0        9.0              0.0        0.0        0.0              0.0       32.0       26.0              0.0       21.0       22.0              0.0       19.0       10.0              0.0       10.0        9.0              0.0        11.0         3.0               0.0         9.0         3.0               0.0         6.0         3.0               0.0         6.0         1.0               0.0         5.0         4.0               0.0         8.0         4.0               0.0         9.0         0.0               0.0        14.0         7.0               0.0         8.0         7.0               0.0        15.0        12.0               0.0        19.0        30.0               0.0        26.0        37.0               0.0        30.0        46.0               0.0        45.0        48.0               0.0        54.0        72.0               0.0        45.0       106.0               0.0        59.0        78.0               0.0        42.0        79.0               0.0        14.0        21.0               0.0         0.0         9.0               0.0         0.0         0.0               0.0  2022    Cuadro12
2      3.0             NaN                002 Tuberculosis y secuelas     1402.0    1007.0     395.0            0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        3.0        1.0              0.0        1.0        0.0              0.0        1.0        3.0              0.0        5.0        3.0              0.0         1.0         0.0               0.0         2.0         3.0               0.0        13.0        12.0               0.0        39.0        18.0               0.0        50.0        13.0               0.0        50.0        23.0               0.0        55.0        14.0               0.0        52.0        17.0               0.0        46.0        16.0               0.0        57.0        18.0               0.0        74.0        34.0               0.0       114.0        35.0               0.0       118.0        36.0               0.0       105.0        43.0               0.0        79.0        34.0               0.0        81.0        35.0               0.0        40.0        30.0               0.0        18.0         2.0               0.0         3.0         5.0               0.0         0.0         0.0               0.0         0.0         0.0               0.0  2022    Cuadro12
----------------------------------------

📁 AÑO 2022 - defunciones_2022_cuadro13.csv
   • Filas: 938
   • Columnas: 30
   • Columnas: ['columna', 'columna_1', 'columna_2', 'columna_3', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1', 'Mujeres_1', 'Indeterminado_1']...
   • Tipos de datos:
float64    26
str         3
int64       1
Name: count, dtype: int64

   Primeras 3 filas:
   columna       columna_1                                  columna_2  columna_3  Hombres  Mujeres  Indeterminado  Hombres_1  Mujeres_1  Indeterminado_1  Hombres_2  Mujeres_2  Indeterminado_2  Hombres_3  Mujeres_3  Indeterminado_3  Hombres_4  Mujeres_4  Indeterminado_4  Hombres_5  Mujeres_5  Indeterminado_5  Hombres_6  Mujeres_6  Indeterminado_6  Hombres_7  Mujeres_7  Indeterminado_7   año hoja_origen
0      3.0  Total Nacional                                      TOTAL     6689.0   3735.0   2947.0            7.0      173.0      137.0              2.0      418.0      355.0              1.0      958.0      719.0              2.0      772.0      639.0              1.0       36.0       18.0              0.0      944.0      761.0              1.0      434.0      318.0              0.0  2022    Cuadro13
1      3.0             NaN  001 Enfermedades infecciosas intestinales      127.0     65.0     62.0            0.0        0.0        0.0              0.0        0.0        0.0              0.0        3.0        5.0              0.0        9.0        9.0              0.0        0.0        0.0              0.0       32.0       26.0              0.0       21.0       22.0              0.0  2022    Cuadro13
2      3.0             NaN                002 Tuberculosis y secuelas        5.0      4.0      1.0            0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        0.0        0.0              0.0        3.0        1.0              0.0        1.0        0.0              0.0  2022    Cuadro13
----------------------------------------

📁 AÑO 2022 - defunciones_2022_cuadro14.csv
   • Filas: 398
   • Columnas: 30
   • Columnas: ['columna', 'columna_1', 'columna_2', 'columna_3', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1', 'Mujeres_1', 'Indeterminado_1']...
   • Tipos de datos:
float64    26
str         3
int64       1
Name: count, dtype: int64

   Primeras 3 filas:
   columna       columna_1     columna_2  columna_3  Hombres  Mujeres  Indeterminado  Hombres_1  Mujeres_1  Indeterminado_1  Hombres_2  Mujeres_2  Indeterminado_2  Hombres_3  Mujeres_3  Indeterminado_3  Hombres_4  Mujeres_4  Indeterminado_4  Hombres_5  Mujeres_5  Indeterminado_5  Hombres_6  Mujeres_6  Indeterminado_6  Hombres_7  Mujeres_7  Indeterminado_7   año hoja_origen
0      3.0  Total Nacional         TOTAL     6689.0   3735.0   2947.0            7.0      173.0      137.0              2.0      418.0      355.0              1.0      958.0      719.0              2.0      772.0      639.0              1.0       36.0       18.0              0.0      944.0      761.0              1.0      434.0      318.0              0.0  2022    Cuadro14
1      3.0             NaN  10 - 14 años       85.0     54.0     31.0            0.0        1.0        3.0              0.0        7.0        5.0              0.0       15.0        8.0              0.0       12.0        5.0              0.0        1.0        0.0              0.0       11.0       10.0              0.0        7.0        0.0              0.0  2022    Cuadro14
2      3.0             NaN  15 - 19 años     1173.0    658.0    514.0            1.0       29.0       27.0              0.0       98.0       67.0              0.0      181.0      118.0              1.0      129.0      109.0              0.0        8.0        4.0              0.0      154.0      148.0              0.0       59.0       41.0              0.0  2022    Cuadro14
----------------------------------------

📁 AÑO 2022 - defunciones_2022_cuadro15.csv
   • Filas: 5,900
   • Columnas: 101
   • Columnas: ['columna', 'columna_1', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1']...
   • Tipos de datos:
float64    96
str         4
int64       1
Name: count, dtype: int64

   Primeras 3 filas:

In [1]:
import pandas as pd
import os
import glob

carpeta_base = 'datasets_defunciones_completos'

def unir_cuadro_especifico(nombre_cuadro):
    """
    Une un cuadro específico de todos los años
    Ej: 'cuadro1', 'cuadro5', 'cuadro11', etc.
    """
    print(f"\n{'='*70}")
    print(f"UNIENDO {nombre_cuadro.upper()} - TODOS LOS AÑOS")
    print('='*70)
    
    dataframes = []
    total_filas = 0
    
    for año in ['2022', '2023', '2024', '2025']:
        carpeta_año = os.path.join(carpeta_base, f'año_{año}')
        patron = os.path.join(carpeta_año, f'*{nombre_cuadro.lower()}*.csv')
        archivos = glob.glob(patron)
        
        if archivos:
            archivo = archivos[0]  # Tomar el primero
            df = pd.read_csv(archivo)
            
            # Asegurar que la columna 'año' existe
            if 'año' not in df.columns:
                df['año'] = año
            
            dataframes.append(df)
            print(f"  ✅ Año {año}: {len(df):,} filas")
            total_filas += len(df)
        else:
            print(f"  ❌ Año {año}: No encontrado")
    
    if dataframes:
        # Unir todos
        df_unido = pd.concat(dataframes, ignore_index=True)
        
        print(f"\n📊 TOTAL UNIDO:")
        print(f"   • Filas totales: {len(df_unido):,}")
        print(f"   • Columnas: {len(df_unido.columns)}")
        print(f"   • Distribución por año:\n{df_unido['año'].value_counts().sort_index()}")
        
        # Guardar
        nombre_archivo = f"todos_los_{nombre_cuadro}.csv"
        df_unido.to_csv(nombre_archivo, index=False, encoding='utf-8-sig')
        print(f"\n💾 Guardado en: {nombre_archivo}")
        
        return df_unido
    else:
        print("❌ No se encontraron datos")
        return None

# UNIR TODOS LOS CUADROS QUE QUIERAS:

# 1. Unir Cuadro 1
df_cuadro1 = unir_cuadro_especifico('cuadro1')

# 2. Unir Cuadro 5 (el más grande)
df_cuadro5 = unir_cuadro_especifico('cuadro5')

# 3. Unir Cuadro 11
df_cuadro11 = unir_cuadro_especifico('cuadro11')

# 4. Unir Cuadro 3
df_cuadro3 = unir_cuadro_especifico('cuadro3')

======================================================================
UNIENDO CUADRO1 - TODOS LOS AÑOS
======================================================================
  ✅ Año 2022: 32 filas
  ✅ Año 2023: 32 filas
  ✅ Año 2024: 32 filas
  ✅ Año 2025: 32 filas

📊 TOTAL UNIDO:
   • Filas totales: 128
   • Columnas: 19
   • Distribución por año:
año
2022    32
2023    32
2024    32
2025    32
Name: count, dtype: int64

💾 Guardado en: todos_los_cuadro1.csv

======================================================================
UNIENDO CUADRO5 - TODOS LOS AÑOS
======================================================================
  ✅ Año 2022: 35,010 filas
  ✅ Año 2023: 34,111 filas
  ✅ Año 2024: 34,606 filas
  ✅ Año 2025: 28,001 filas

📊 TOTAL UNIDO:
   • Filas totales: 131,728
   • Columnas: 38
   • Distribución por año:
año
2022    35010
2023    34111
2024    34606
2025    28001
Name: count, dtype: int64

💾 Guardado en: todos_los_cuadro5.csv

======================================================================
UNIENDO CUADRO11 - TODOS LOS AÑOS
======================================================================
  ✅ Año 2022: 3,153 filas
  ✅ Año 2023: 3,137 filas
  ✅ Año 2024: 3,142 filas
  ✅ Año 2025: 2,994 filas

📊 TOTAL UNIDO:
   • Filas totales: 12,426
   • Columnas: 99
   • Distribución por año:
año
2022    3153
2023    3137
2024    3142
2025    2994
Name: count, dtype: int64

💾 Guardado en: todos_los_cuadro11.csv

======================================================================
UNIENDO CUADRO3 - TODOS LOS AÑOS
======================================================================
  ✅ Año 2022: 5,942 filas
  ✅ Año 2023: 5,947 filas
  ✅ Año 2024: 5,947 filas
  ❌ Año 2025: No encontrado

📊 TOTAL UNIDO:
   • Filas totales: 17,836
   • Columnas: 38
   • Distribución por año:
año
2022    5942
2023    5947
2024    5947
Name: count, dtype: int64

💾 Guardado en: todos_los_cuadro3.csv

In [2]:
print("datos cuadro 1:  ")
df_cuadro1.head()

datos cuadro 1:

,columna,columna_1,Hombres,Mujeres,Indeterminado,Hombres_1,Mujeres_1,Indeterminado_1,Hombres_2,Mujeres_2,Indeterminado_2,Hombres_3,Mujeres_3,Indeterminado_3,Hombres_4,Mujeres_4,Indeterminado_4,año,hoja_origen
0,Total Nacional,287251.0,159171.0,128030.0,50.0,139563.0,118160.0,28.0,4524.0,2642.0,0.0,14240.0,6775.0,14.0,844.0,453.0,8.0,2022,Cuadro1
1,Menor 1 hora,312.0,173.0,137.0,2.0,167.0,132.0,2.0,0.0,0.0,0.0,6.0,5.0,0.0,0.0,0.0,0.0,2022,Cuadro1
2,De 1 a 23 horas,774.0,418.0,355.0,1.0,405.0,348.0,1.0,4.0,0.0,0.0,8.0,7.0,0.0,1.0,0.0,0.0,2022,Cuadro1
3,De 1 a 6 días,1679.0,958.0,719.0,2.0,946.0,704.0,2.0,3.0,1.0,0.0,5.0,11.0,0.0,4.0,3.0,0.0,2022,Cuadro1
4,De 7 a 27 días,1412.0,772.0,639.0,1.0,758.0,627.0,1.0,4.0,1.0,0.0,8.0,8.0,0.0,2.0,3.0,0.0,2022,Cuadro1

In [3]:
print("datos cuadro 5:  ")
df_cuadro5.head()

datos cuadro 5:

,columna,columna_1,columna_2,columna_3,columna_4,columna_5,Hombres,Mujeres,Indeterminado,Hombres_1,...,Mujeres_7,Indeterminado_7,Hombres_8,Mujeres_8,Indeterminado_8,Hombres_9,Mujeres_9,Indeterminado_9,año,hoja_origen
0,3.0,3000.0,Total Nacional,NaN,TOTAL,287251.0,159171.0,128030.0,50.0,3735.0,...,39300.0,3.0,824.0,1822.0,3.0,13.0,2.0,13.0,2022,Cuadro5
1,3.0,3000.0,NaN,NaN,"000 Signos, síntomas y afecciones mal definidas",3704.0,2272.0,1414.0,18.0,82.0,...,443.0,1.0,30.0,49.0,1.0,6.0,2.0,10.0,2022,Cuadro5
2,3.0,3000.0,NaN,NaN,101 Enfermedades infecciosas intestinales,1170.0,519.0,651.0,0.0,65.0,...,178.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,2022,Cuadro5
3,3.0,3000.0,NaN,NaN,102 Tuberculosis,1351.0,972.0,379.0,0.0,4.0,...,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro5
4,3.0,3000.0,NaN,NaN,103 Ciertas enfermedades transmisibles por vec...,344.0,200.0,144.0,0.0,4.0,...,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro5

In [4]:
print("datos cuadro 3:  ")
df_cuadro3.head()

datos cuadro 3:

,columna,columna_1,columna_2,columna_3,columna_4,columna_5,Hombres,Mujeres,Indeterminado,Hombres_1,...,Mujeres_7,Indeterminado_7,Hombres_8,Mujeres_8,Indeterminado_8,Hombres_9,Mujeres_9,Indeterminado_9,año,hoja_origen
0,3.0,3000.0,Total Nacional,NaN,TOTAL,287251.0,159171.0,128030.0,50.0,3735.0,...,39300.0,3.0,824.0,1822.0,3.0,13.0,2.0,13.0,2022,Cuadro3
1,3.0,3000.0,NaN,NaN,Cabecera municipal,257751.0,139563.0,118160.0,28.0,3569.0,...,35741.0,2.0,694.0,1627.0,0.0,5.0,1.0,6.0,2022,Cuadro3
2,3.0,3000.0,NaN,NaN,Centro poblado,7166.0,4524.0,2642.0,0.0,38.0,...,1068.0,0.0,36.0,59.0,0.0,1.0,0.0,0.0,2022,Cuadro3
3,3.0,3000.0,NaN,NaN,Rural disperso,21029.0,14240.0,6775.0,14.0,114.0,...,2337.0,1.0,85.0,129.0,1.0,2.0,0.0,2.0,2022,Cuadro3
4,3.0,3000.0,NaN,NaN,Sin información,1305.0,844.0,453.0,8.0,14.0,...,154.0,0.0,9.0,7.0,2.0,5.0,1.0,5.0,2022,Cuadro3

In [6]:
print("datos cuadro 11:  ")
df_cuadro11.head(10)

datos cuadro 11:

,columna,columna_1,columna_2,columna_3,Hombres,Mujeres,Indeterminado,Hombres_1,Mujeres_1,Indeterminado_1,...,Mujeres_28,Indeterminado_28,Hombres_29,Mujeres_29,Indeterminado_29,Hombres_30,Mujeres_30,Indeterminado_30,año,hoja_origen
0,3.0,Total Nacional,TOTAL,287251.0,159171.0,128030.0,50.0,173.0,137.0,2.0,...,6403.0,0.0,824.0,1822.0,3.0,13.0,2.0,13.0,2022,Cuadro11
1,3.0,NaN,001 Enfermedades infecciosas intestinales,1170.0,519.0,651.0,0.0,0.0,0.0,0.0,...,21.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,2022,Cuadro11
2,3.0,NaN,002 Tuberculosis y secuelas,1402.0,1007.0,395.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro11
3,3.0,NaN,003 Ciertas enfermedades transmitidas por vect...,344.0,200.0,144.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro11
4,3.0,NaN,004 Ciertas enfermedades inmunoprevenibles,46.0,29.0,17.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro11
5,3.0,NaN,"005 Septicemia, excepto neonatal",831.0,395.0,436.0,0.0,0.0,0.0,0.0,...,11.0,0.0,3.0,5.0,0.0,0.0,0.0,0.0,2022,Cuadro11
6,3.0,NaN,006 Todas las demás enfermedades bacterianas,442.0,261.0,181.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2022,Cuadro11
7,3.0,NaN,007 Sífilis y otras enfermedades venéreas,52.0,32.0,20.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro11
8,3.0,NaN,008 Hepatitis viral y secuelas,122.0,70.0,52.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro11
9,3.0,NaN,009 Enfermedad por el VIH (SIDA),2298.0,1793.0,505.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022,Cuadro11

In [7]:
# Buscar filas relevantes
terminos = ["materna", "embarazo", "parto", "desnutri"]
for t in terminos:
    resultado = df_cuadro11[df_cuadro11["columna_2"].astype(str).str.lower().str.contains(t, na=False)]
    print(f"\n--- '{t}' ---")
    print(resultado[["columna_2", "columna_3", "Hombres", "Mujeres", "año"]].to_string())

--- 'materna' ---
                                                                columna_2  columna_3  Hombres  Mujeres   año
79     079 Feto y recién nacido afectados por ciertas afecciones maternas      156.0     87.0     69.0  2022
185    079 Feto y recién nacido afectados por ciertas afecciones maternas       11.0      8.0      3.0  2022
289    079 Feto y recién nacido afectados por ciertas afecciones maternas        7.0      2.0      5.0  2022
394    079 Feto y recién nacido afectados por ciertas afecciones maternas       22.0     12.0     10.0  2022
496    079 Feto y recién nacido afectados por ciertas afecciones maternas       12.0      8.0      4.0  2022
596    079 Feto y recién nacido afectados por ciertas afecciones maternas        5.0      2.0      3.0  2022
696    079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      2.0      1.0  2022
790    079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2022
993    079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      2.0      0.0  2022
1095   079 Feto y recién nacido afectados por ciertas afecciones maternas        6.0      2.0      4.0  2022
1195   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      2.0      0.0  2022
1292   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2022
1394   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      2.0      2.0  2022
1495   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      3.0      0.0  2022
1598   079 Feto y recién nacido afectados por ciertas afecciones maternas        7.0      1.0      6.0  2022
1700   079 Feto y recién nacido afectados por ciertas afecciones maternas        5.0      2.0      3.0  2022
1805   079 Feto y recién nacido afectados por ciertas afecciones maternas        7.0      5.0      2.0  2022
1910   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2022
2013   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2022
2116   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      1.0      2.0  2022
2219   079 Feto y recién nacido afectados por ciertas afecciones maternas        8.0      6.0      2.0  2022
2324   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      2.0      0.0  2022
2426   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      1.0      3.0  2022
2531   079 Feto y recién nacido afectados por ciertas afecciones maternas       31.0     17.0     14.0  2022
2619   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2022
2712   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      0.0      2.0  2022
2800   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      3.0      0.0  2022
2927   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2022
3232   079 Feto y recién nacido afectados por ciertas afecciones maternas      127.0     72.0     55.0  2023
3338   079 Feto y recién nacido afectados por ciertas afecciones maternas        6.0      2.0      4.0  2023
3443   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      1.0      3.0  2023
3548   079 Feto y recién nacido afectados por ciertas afecciones maternas       31.0     18.0     13.0  2023
3653   079 Feto y recién nacido afectados por ciertas afecciones maternas        9.0      5.0      4.0  2023
3756   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      2.0      0.0  2023
4061   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2023
4164   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      2.0      1.0  2023
4269   079 Feto y recién nacido afectados por ciertas afecciones maternas        7.0      3.0      4.0  2023
4373   079 Feto y recién nacido afectados por ciertas afecciones maternas        5.0      3.0      2.0  2023
4570   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      2.0      2.0  2023
4671   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2023
4772   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2023
4876   079 Feto y recién nacido afectados por ciertas afecciones maternas        6.0      5.0      1.0  2023
4981   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      2.0      2.0  2023
5185   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2023
5388   079 Feto y recién nacido afectados por ciertas afecciones maternas        5.0      2.0      3.0  2023
5489   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      1.0      2.0  2023
5592   079 Feto y recién nacido afectados por ciertas afecciones maternas        5.0      4.0      1.0  2023
5697   079 Feto y recién nacido afectados por ciertas afecciones maternas       23.0     16.0      7.0  2023
5790   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2023
5884   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2023
5974   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2023
6134   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2023
6369   079 Feto y recién nacido afectados por ciertas afecciones maternas      137.0     71.0     66.0  2024
6475   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      1.0      3.0  2024
6580   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      1.0      2.0  2024
6683   079 Feto y recién nacido afectados por ciertas afecciones maternas       27.0     12.0     15.0  2024
6787   079 Feto y recién nacido afectados por ciertas afecciones maternas        8.0      6.0      2.0  2024
6888   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      2.0      0.0  2024
6990   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2024
7089   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      2.0      0.0  2024
7189   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2024
7290   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2024
7394   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      1.0      2.0  2024
7497   079 Feto y recién nacido afectados por ciertas afecciones maternas        8.0      5.0      3.0  2024
7693   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2024
7794   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      2.0      0.0  2024
7895   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      2.0      1.0  2024
8000   079 Feto y recién nacido afectados por ciertas afecciones maternas        5.0      3.0      2.0  2024
8104   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      1.0      3.0  2024
8209   079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      1.0      2.0  2024
8411   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      2.0      2.0  2024
8514   079 Feto y recién nacido afectados por ciertas afecciones maternas        7.0      3.0      4.0  2024
8615   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2024
8718   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      1.0      3.0  2024
8822   079 Feto y recién nacido afectados por ciertas afecciones maternas       34.0     18.0     16.0  2024
9091   079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      3.0      1.0  2024
9211   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2024
9366   079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2024
9511   079 Feto y recién nacido afectados por ciertas afecciones maternas       72.0     46.0     26.0  2025
9617   079 Feto y recién nacido afectados por ciertas afecciones maternas        6.0      4.0      2.0  2025
9722   079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2025
9824   079 Feto y recién nacido afectados por ciertas afecciones maternas       17.0     14.0      3.0  2025
9926   079 Feto y recién nacido afectados por ciertas afecciones maternas        6.0      5.0      1.0  2025
10026  079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      0.0      2.0  2025
10215  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2025
10410  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2025
10510  079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2025
10613  079 Feto y recién nacido afectados por ciertas afecciones maternas        8.0      5.0      3.0  2025
10799  079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2025
10894  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2025
10992  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2025
11093  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2025
11197  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2025
11397  079 Feto y recién nacido afectados por ciertas afecciones maternas        3.0      2.0      1.0  2025
11590  079 Feto y recién nacido afectados por ciertas afecciones maternas        2.0      1.0      1.0  2025
11893  079 Feto y recién nacido afectados por ciertas afecciones maternas       10.0      7.0      3.0  2025
11983  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      0.0      1.0  2025
12068  079 Feto y recién nacido afectados por ciertas afecciones maternas        4.0      1.0      3.0  2025
12149  079 Feto y recién nacido afectados por ciertas afecciones maternas        1.0      1.0      0.0  2025

--- 'embarazo' ---
                             columna_2  columna_3  Hombres  Mujeres   año
78     078 Embarazo, parto y puerperio      464.0      0.0    464.0  2022
184    078 Embarazo, parto y puerperio       39.0      0.0     39.0  2022
288    078 Embarazo, parto y puerperio       48.0      0.0     48.0  2022
393    078 Embarazo, parto y puerperio       52.0      0.0     52.0  2022
495    078 Embarazo, parto y puerperio       27.0      0.0     27.0  2022
595    078 Embarazo, parto y puerperio       10.0      0.0     10.0  2022
695    078 Embarazo, parto y puerperio        1.0      0.0      1.0  2022
789    078 Embarazo, parto y puerperio        2.0      0.0      2.0  2022
888    078 Embarazo, parto y puerperio       10.0      0.0     10.0  2022
992    078 Embarazo, parto y puerperio       28.0      0.0     28.0  2022
1094   078 Embarazo, parto y puerperio       29.0      0.0     29.0  2022
1194   078 Embarazo, parto y puerperio       12.0      0.0     12.0  2022
1291   078 Embarazo, parto y puerperio       13.0      0.0     13.0  2022
1393   078 Embarazo, parto y puerperio       15.0      0.0     15.0  2022
1494   078 Embarazo, parto y puerperio       32.0      0.0     32.0  2022
1597   078 Embarazo, parto y puerperio       26.0      0.0     26.0  2022
1699   078 Embarazo, parto y puerperio        5.0      0.0      5.0  2022
1804   078 Embarazo, parto y puerperio       19.0      0.0     19.0  2022
1909   078 Embarazo, parto y puerperio       20.0      0.0     20.0  2022
2012   078 Embarazo, parto y puerperio        5.0      0.0      5.0  2022
2115   078 Embarazo, parto y puerperio        3.0      0.0      3.0  2022
2218   078 Embarazo, parto y puerperio        8.0      0.0      8.0  2022
2323   078 Embarazo, parto y puerperio       11.0      0.0     11.0  2022
2425   078 Embarazo, parto y puerperio        7.0      0.0      7.0  2022
2530   078 Embarazo, parto y puerperio       25.0      0.0     25.0  2022
2618   078 Embarazo, parto y puerperio        7.0      0.0      7.0  2022
2711   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2022
2799   078 Embarazo, parto y puerperio        3.0      0.0      3.0  2022
2926   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2022
2984   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2022
3084   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2022
3136   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2022
3231   078 Embarazo, parto y puerperio      415.0      0.0    415.0  2023
3337   078 Embarazo, parto y puerperio       34.0      0.0     34.0  2023
3442   078 Embarazo, parto y puerperio       32.0      0.0     32.0  2023
3547   078 Embarazo, parto y puerperio       50.0      0.0     50.0  2023
3652   078 Embarazo, parto y puerperio       27.0      0.0     27.0  2023
3755   078 Embarazo, parto y puerperio       10.0      0.0     10.0  2023
3861   078 Embarazo, parto y puerperio        4.0      0.0      4.0  2023
3957   078 Embarazo, parto y puerperio        3.0      0.0      3.0  2023
4060   078 Embarazo, parto y puerperio        8.0      0.0      8.0  2023
4163   078 Embarazo, parto y puerperio       18.0      0.0     18.0  2023
4268   078 Embarazo, parto y puerperio       19.0      0.0     19.0  2023
4372   078 Embarazo, parto y puerperio        4.0      0.0      4.0  2023
4467   078 Embarazo, parto y puerperio       13.0      0.0     13.0  2023
4569   078 Embarazo, parto y puerperio       11.0      0.0     11.0  2023
4670   078 Embarazo, parto y puerperio       30.0      0.0     30.0  2023
4771   078 Embarazo, parto y puerperio       25.0      0.0     25.0  2023
4875   078 Embarazo, parto y puerperio        9.0      0.0      9.0  2023
4980   078 Embarazo, parto y puerperio       16.0      0.0     16.0  2023
5083   078 Embarazo, parto y puerperio       14.0      0.0     14.0  2023
5184   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2023
5285   078 Embarazo, parto y puerperio        4.0      0.0      4.0  2023
5387   078 Embarazo, parto y puerperio       15.0      0.0     15.0  2023
5488   078 Embarazo, parto y puerperio       12.0      0.0     12.0  2023
5591   078 Embarazo, parto y puerperio       11.0      0.0     11.0  2023
5696   078 Embarazo, parto y puerperio       29.0      0.0     29.0  2023
5789   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2023
5883   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2023
5973   078 Embarazo, parto y puerperio        4.0      0.0      4.0  2023
6083   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2023
6133   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2023
6193   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2023
6275   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2023
6368   078 Embarazo, parto y puerperio      355.0      0.0    355.0  2024
6474   078 Embarazo, parto y puerperio       32.0      0.0     32.0  2024
6579   078 Embarazo, parto y puerperio       29.0      0.0     29.0  2024
6682   078 Embarazo, parto y puerperio       48.0      0.0     48.0  2024
6786   078 Embarazo, parto y puerperio       23.0      0.0     23.0  2024
6887   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2024
6989   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2024
7088   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2024
7188   078 Embarazo, parto y puerperio        7.0      0.0      7.0  2024
7289   078 Embarazo, parto y puerperio       22.0      0.0     22.0  2024
7393   078 Embarazo, parto y puerperio       17.0      0.0     17.0  2024
7496   078 Embarazo, parto y puerperio       13.0      0.0     13.0  2024
7592   078 Embarazo, parto y puerperio       17.0      0.0     17.0  2024
7692   078 Embarazo, parto y puerperio        8.0      0.0      8.0  2024
7793   078 Embarazo, parto y puerperio       28.0      0.0     28.0  2024
7894   078 Embarazo, parto y puerperio       11.0      0.0     11.0  2024
7999   078 Embarazo, parto y puerperio        8.0      0.0      8.0  2024
8103   078 Embarazo, parto y puerperio       14.0      0.0     14.0  2024
8208   078 Embarazo, parto y puerperio       11.0      0.0     11.0  2024
8310   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2024
8410   078 Embarazo, parto y puerperio        6.0      0.0      6.0  2024
8513   078 Embarazo, parto y puerperio       10.0      0.0     10.0  2024
8614   078 Embarazo, parto y puerperio        5.0      0.0      5.0  2024
8717   078 Embarazo, parto y puerperio        8.0      0.0      8.0  2024
8821   078 Embarazo, parto y puerperio       21.0      0.0     21.0  2024
9004   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2024
9090   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2024
9210   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2024
9263   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2024
9328   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2024
9365   078 Embarazo, parto y puerperio        1.0      0.0      1.0  2024
9415   078 Embarazo, parto y puerperio        2.0      0.0      2.0  2024
9510   078 Embarazo, parto y puerperio      174.0      0.0    174.0  2025
9616   078 Embarazo, parto y puerperio       17.0      0.0     17.0  2025
9721   078 Embarazo, parto y puerperio       18.0      0.0     18.0  2025
9823   078 Embarazo, parto y puerperio       20.0      0.0     20.0  2025
9925   078 Embarazo, parto y puerperio       11.0      0.0     11.0  2025
10124  078 Embarazo, parto y puerperio        2.0      0.0      2.0  2025
10409  078 Embarazo, parto y puerperio       10.0      0.0     10.0  2025
10509  078 Embarazo, parto y puerperio        8.0      0.0      8.0  2025
10612  078 Embarazo, parto y puerperio        7.0      0.0      7.0  2025
10699  078 Embarazo, parto y puerperio        3.0      0.0      3.0  2025
10798  078 Embarazo, parto y puerperio        5.0      0.0      5.0  2025
10893  078 Embarazo, parto y puerperio        7.0      0.0      7.0  2025
10991  078 Embarazo, parto y puerperio        4.0      0.0      4.0  2025
11092  078 Embarazo, parto y puerperio        6.0      0.0      6.0  2025
11196  078 Embarazo, parto y puerperio        6.0      0.0      6.0  2025
11300  078 Embarazo, parto y puerperio        8.0      0.0      8.0  2025
11396  078 Embarazo, parto y puerperio        1.0      0.0      1.0  2025
11492  078 Embarazo, parto y puerperio        7.0      0.0      7.0  2025
11589  078 Embarazo, parto y puerperio        7.0      0.0      7.0  2025
11690  078 Embarazo, parto y puerperio        4.0      0.0      4.0  2025
11789  078 Embarazo, parto y puerperio        2.0      0.0      2.0  2025
11892  078 Embarazo, parto y puerperio        8.0      0.0      8.0  2025
11982  078 Embarazo, parto y puerperio        3.0      0.0      3.0  2025
12067  078 Embarazo, parto y puerperio        3.0      0.0      3.0  2025
12148  078 Embarazo, parto y puerperio        3.0      0.0      3.0  2025

In [8]:
# Ver que hay en columna_1 para las filas de embarazo
embarazo = df_cuadro11[df_cuadro11["columna_2"].astype(str).str.contains("078", na=False)]
print(embarazo[["columna", "columna_1", "columna_2", "columna_3", "Hombres", "Mujeres", "año"]].head(10).to_string())

     columna columna_1                        columna_2  columna_3  Hombres  Mujeres   año
78       3.0       NaN  078 Embarazo, parto y puerperio      464.0      0.0    464.0  2022
184      5.0       NaN  078 Embarazo, parto y puerperio       39.0      0.0     39.0  2022
288      8.0       NaN  078 Embarazo, parto y puerperio       48.0      0.0     48.0  2022
393     11.0       NaN  078 Embarazo, parto y puerperio       52.0      0.0     52.0  2022
495     13.0       NaN  078 Embarazo, parto y puerperio       27.0      0.0     27.0  2022
595     15.0       NaN  078 Embarazo, parto y puerperio       10.0      0.0     10.0  2022
695     17.0       NaN  078 Embarazo, parto y puerperio        1.0      0.0      1.0  2022
789     18.0       NaN  078 Embarazo, parto y puerperio        2.0      0.0      2.0  2022
888     19.0       NaN  078 Embarazo, parto y puerperio       10.0      0.0     10.0  2022
992     20.0       NaN  078 Embarazo, parto y puerperio       28.0      0.0     28.0  2022

In [9]:
# Ver todas las columnas disponibles
print(df_cuadro11.columns.tolist())

# Ver las primeras filas del cuadro completo para entender la geografía
embarazo = df_cuadro11[df_cuadro11["columna_2"].astype(str).str.contains("078", na=False)]
print(embarazo[["columna", "columna_1", "columna_2", "columna_3", "Hombres", "Mujeres", "año"]].iloc[:5].to_string())

# Cuantos valores unicos tiene columna_3 para embarazo en 2022
e2022 = embarazo[embarazo["año"] == 2022]
print(f"\nTotal filas embarazo 2022: {len(e2022)}")
print(f"Suma columna_3: {e2022['columna_3'].sum()}")
print(f"Maximo columna_3: {e2022['columna_3'].max()}")

['columna', 'columna_1', 'columna_2', 'columna_3', 'Hombres', 'Mujeres', 'Indeterminado', 'Hombres_1', 'Mujeres_1', 'Indeterminado_1', 'Hombres_2', 'Mujeres_2', 'Indeterminado_2', 'Hombres_3', 'Mujeres_3', 'Indeterminado_3', 'Hombres_4', 'Mujeres_4', 'Indeterminado_4', 'Hombres_5', 'Mujeres_5', 'Indeterminado_5', 'Hombres_6', 'Mujeres_6', 'Indeterminado_6', 'Hombres_7', 'Mujeres_7', 'Indeterminado_7', 'Hombres_8', 'Mujeres_8', 'Indeterminado_8', 'Hombres_9', 'Mujeres_9', 'Indeterminado_9', 'Hombres_10', 'Mujeres_10', 'Indeterminado_10', 'Hombres_11', 'Mujeres_11', 'Indeterminado_11', 'Hombres_12', 'Mujeres_12', 'Indeterminado_12', 'Hombres_13', 'Mujeres_13', 'Indeterminado_13', 'Hombres_14', 'Mujeres_14', 'Indeterminado_14', 'Hombres_15', 'Mujeres_15', 'Indeterminado_15', 'Hombres_16', 'Mujeres_16', 'Indeterminado_16', 'Hombres_17', 'Mujeres_17', 'Indeterminado_17', 'Hombres_18', 'Mujeres_18', 'Indeterminado_18', 'Hombres_19', 'Mujeres_19', 'Indeterminado_19', 'Hombres_20', 'Mujeres_20', 'Indeterminado_20', 'Hombres_21', 'Mujeres_21', 'Indeterminado_21', 'Hombres_22', 'Mujeres_22', 'Indeterminado_22', 'Hombres_23', 'Mujeres_23', 'Indeterminado_23', 'Hombres_24', 'Mujeres_24', 'Indeterminado_24', 'Hombres_25', 'Mujeres_25', 'Indeterminado_25', 'Hombres_26', 'Mujeres_26', 'Indeterminado_26', 'Hombres_27', 'Mujeres_27', 'Indeterminado_27', 'Hombres_28', 'Mujeres_28', 'Indeterminado_28', 'Hombres_29', 'Mujeres_29', 'Indeterminado_29', 'Hombres_30', 'Mujeres_30', 'Indeterminado_30', 'año', 'hoja_origen']
     columna columna_1                        columna_2  columna_3  Hombres  Mujeres   año
78       3.0       NaN  078 Embarazo, parto y puerperio      464.0      0.0    464.0  2022
184      5.0       NaN  078 Embarazo, parto y puerperio       39.0      0.0     39.0  2022
288      8.0       NaN  078 Embarazo, parto y puerperio       48.0      0.0     48.0  2022
393     11.0       NaN  078 Embarazo, parto y puerperio       52.0      0.0     52.0  2022
495     13.0       NaN  078 Embarazo, parto y puerperio       27.0      0.0     27.0  2022

Total filas embarazo 2022: 32
Suma columna_3: 928.0
Maximo columna_3: 464.0

In [10]:
import pandas as pd
import os
import glob

# ============================================
# CONFIGURACIÓN
# ============================================
carpeta_base = 'data/datos_completos/nacimientos'

def inspeccionar_estructura_nacimientos():
    """
    Inspecciona la estructura de todos los cuadros de nacimientos
    Muestra número de columnas, nombres y una muestra de datos
    """
    print("\n" + "="*80)
    print("📊 INSPECCIÓN DE ESTRUCTURA - DATOS DE NACIMIENTOS")
    print("="*80)
    
    # Lista de cuadros de nacimientos
    cuadros_nacimientos = ['cuadro1', 'cuadro3', 'cuadro5', 'cuadro6a', 'cuadro11', 'cuadro13']
    años = ['2022', '2023', '2024', '2025']
    
    resumen_estructura = []
    
    for cuadro in cuadros_nacimientos:
        print(f"\n{'#'*60}")
        print(f"📋 ANALIZANDO {cuadro.upper()}")
        print('#'*60)
        
        estructuras_por_año = {}
        
        for año in años:
            carpeta_año = os.path.join(carpeta_base, f'año_{año}')
            patron = os.path.join(carpeta_año, f'nacimientos_{año}_{cuadro}*.csv')
            archivos = glob.glob(patron)
            
            if archivos:
                archivo = archivos[0]
                df = pd.read_csv(archivo, nrows=5)  # Leer solo 5 filas para inspección
                
                # Información básica
                print(f"\n📁 AÑO {año}:")
                print(f"   • Archivo: {os.path.basename(archivo)}")
                print(f"   • Filas totales: {len(pd.read_csv(archivo)):,}")
                print(f"   • Columnas: {len(df.columns)}")
                
                # Mostrar primeras columnas
                print(f"   • Primeras 10 columnas: {df.columns[:10].tolist()}")
                
                # Tipos de datos
                print(f"   • Tipos de datos:")
                tipos = df.dtypes.value_counts()
                for tipo, count in tipos.items():
                    print(f"      - {tipo}: {count} columnas")
                
                # Guardar para resumen
                estructuras_por_año[año] = {
                    'columnas': len(df.columns),
                    'nombres_columnas': list(df.columns),
                    'tipos': dict(df.dtypes.value_counts())
                }
                
                # Mostrar muestra de datos
                print(f"\n   📝 Muestra de datos (primeras 3 filas):")
                print(df.head(3).to_string())
                print("-" * 40)
            else:
                print(f"\n❌ AÑO {año}: No encontrado")
        
        # Resumen del cuadro
        if estructuras_por_año:
            print(f"\n📊 RESUMEN {cuadro.upper()} - COMPARATIVA POR AÑOS:")
            
            # Verificar consistencia de columnas entre años
            columnas_por_año = {año: info['columnas'] for año, info in estructuras_por_año.items()}
            print(f"   • Columnas por año: {columnas_por_año}")
            
            # Verificar si todas tienen las mismas columnas
            if len(set(columnas_por_año.values())) == 1:
                print(f"   ✅ TODOS LOS AÑOS TIENEN {list(columnas_por_año.values())[0]} COLUMNAS")
            else:
                print(f"   ⚠️ DIFERENTE NÚMERO DE COLUMNAS ENTRE AÑOS")
            
            # Guardar en resumen general
            resumen_estructura.append({
                'cuadro': cuadro,
                'columnas_2022': estructuras_por_año.get('2022', {}).get('columnas', 0),
                'columnas_2023': estructuras_por_año.get('2023', {}).get('columnas', 0),
                'columnas_2024': estructuras_por_año.get('2024', {}).get('columnas', 0),
                'columnas_2025': estructuras_por_año.get('2025', {}).get('columnas', 0)
            })
    
    # ============================================
    # RESUMEN GENERAL
    # ============================================
    print("\n" + "="*80)
    print("📈 RESUMEN GENERAL - ESTRUCTURA DE NACIMIENTOS")
    print("="*80)
    
    resumen_df = pd.DataFrame(resumen_estructura)
    print(resumen_df.to_string(index=False))
    
    # Guardar resumen
    resumen_df.to_csv('estructura_nacimientos.csv', index=False, encoding='utf-8-sig')
    print(f"\n💾 Resumen guardado en: estructura_nacimientos.csv")
    
    return resumen_df

# ============================================
# FUNCIÓN PARA VER DETALLE DE COLUMNAS
# ============================================
def ver_detalle_columnas_nacimientos(cuadro_especifico=None):
    """
    Muestra el detalle completo de columnas para cada cuadro
    """
    print("\n" + "="*80)
    print("🔍 DETALLE DE COLUMNAS POR CUADRO")
    print("="*80)
    
    cuadros = [cuadro_especifico] if cuadro_especifico else ['cuadro1', 'cuadro3', 'cuadro5', 'cuadro6a', 'cuadro11', 'cuadro13']
    año_referencia = '2024'  # Usar 2024 como referencia
    
    for cuadro in cuadros:
        carpeta_año = os.path.join(carpeta_base, f'año_{año_referencia}')
        patron = os.path.join(carpeta_año, f'nacimientos_{año_referencia}_{cuadro}*.csv')
        archivos = glob.glob(patron)
        
        if archivos:
            archivo = archivos[0]
            df = pd.read_csv(archivo)
            
            print(f"\n{'#'*60}")
            print(f"📋 {cuadro.upper()} - AÑO {año_referencia}")
            print('#'*60)
            print(f"Total columnas: {len(df.columns)}")
            
            # Mostrar todas las columnas en grupos
            print("\n📌 LISTADO COMPLETO DE COLUMNAS:")
            for i, col in enumerate(df.columns, 1):
                print(f"  {i:3d}. {col}")
            
            # Mostrar tipos de datos
            print(f"\n📊 TIPOS DE DATOS:")
            tipos = df.dtypes.value_counts()
            for tipo, count in tipos.items():
                print(f"  • {tipo}: {count} columnas")
            
            # Mostrar estadísticas básicas de las primeras columnas numéricas
            print(f"\n📈 ESTADÍSTICAS BÁSICAS (primeras columnas numéricas):")
            columnas_numericas = df.select_dtypes(include=[np.number]).columns[:5]
            if len(columnas_numericas) > 0:
                print(df[columnas_numericas].describe().to_string())
        else:
            print(f"\n❌ {cuadro} no encontrado para año {año_referencia}")

# ============================================
# FUNCIÓN PARA VERIFICAR CONSISTENCIA ENTRE AÑOS
# ============================================
def verificar_consistencia_nacimientos():
    """
    Verifica si las columnas son consistentes entre años para cada cuadro
    """
    print("\n" + "="*80)
    print("🔄 VERIFICACIÓN DE CONSISTENCIA ENTRE AÑOS")
    print("="*80)
    
    cuadros = ['cuadro1', 'cuadro3', 'cuadro5', 'cuadro6a', 'cuadro11', 'cuadro13']
    años = ['2022', '2023', '2024', '2025']
    
    for cuadro in cuadros:
        print(f"\n📋 {cuadro.upper()}:")
        
        columnas_por_año = {}
        for año in años:
            carpeta_año = os.path.join(carpeta_base, f'año_{año}')
            patron = os.path.join(carpeta_año, f'nacimientos_{año}_{cuadro}*.csv')
            archivos = glob.glob(patron)
            
            if archivos:
                df = pd.read_csv(archivos[0], nrows=1)
                columnas_por_año[año] = set(df.columns)
                print(f"  • {año}: {len(df.columns)} columnas")
        
        # Verificar consistencia
        if len(columnas_por_año) == len(años):
            primera = list(columnas_por_año.values())[0]
            todas_iguales = all(cols == primera for cols in columnas_por_año.values())
            
            if todas_iguales:
                print(f"  ✅ CONSISTENTE: Mismas columnas en todos los años")
            else:
                print(f"  ⚠️ INCONSISTENTE: Diferencias entre años")
                
                # Mostrar diferencias
                for año, cols in columnas_por_año.items():
                    if cols != primera:
                        print(f"     {año} difiere: {primera - cols} (faltan) | {cols - primera} (extra)")

# ============================================
# EJECUTAR INSPECCIÓN
# ============================================
if __name__ == "__main__":
    import numpy as np
    
    print("\n" + "🚀"*20)
    print("   INSPECCIÓN DE DATOS DE NACIMIENTOS")
    print("🚀"*20)
    
    # 1. Inspección general de estructura
    resumen = inspeccionar_estructura_nacimientos()
    
    # 2. Ver detalle de columnas para cuadros específicos
    print("\n" + "🔍"*20)
    print("   DETALLE POR CUADRO")
    print("🔍"*20)
    
    # Ver cada cuadro individualmente
    for cuadro in ['cuadro1', 'cuadro3', 'cuadro5', 'cuadro6a', 'cuadro11', 'cuadro13']:
        ver_detalle_columnas_nacimientos(cuadro)
    
    # 3. Verificar consistencia entre años
    verificar_consistencia_nacimientos()
    
    print("\n" + "✅"*20)
    print("   INSPECCIÓN COMPLETADA")
    print("✅"*20)

🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
   INSPECCIÓN DE DATOS DE NACIMIENTOS
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

================================================================================
📊 INSPECCIÓN DE ESTRUCTURA - DATOS DE NACIMIENTOS
================================================================================

############################################################
📋 ANALIZANDO CUADRO1
############################################################

📁 AÑO 2022:
   • Archivo: nacimientos_2022_cuadro1.csv
   • Filas totales: 14
   • Columnas: 20
   • Primeras 10 columnas: ['CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, total nacional', 'columna', 'columna_1', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
  CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, total nacional columna columna_1 columna_2      columna_3           columna_4 columna_5      columna_6       columna_7 columna_8      columna_9      columna_10 columna_11     columna_12       columna_13 columna_14     columna_15   año         tipo hoja_origen
0                                                                              Grupo de edad de la madre   Total     Total       NaN            NaN  Cabecera municipal       NaN            NaN  Centro poblado       NaN            NaN  Rural disperso        NaN            NaN  Sin información        NaN            NaN  2022  nacimientos     Cuadro1
1                                                                                                    NaN     NaN   Hombres   Mujeres  Indeterminado             Hombres   Mujeres  Indeterminado         Hombres   Mujeres  Indeterminado         Hombres    Mujeres  Indeterminado          Hombres    Mujeres  Indeterminado  2022  nacimientos     Cuadro1
2                                                                                         Total Nacional   46942     23986     22955              1               23730     22682              1             105       109              0             151        164              0                0          0              0  2022  nacimientos     Cuadro1
----------------------------------------

📁 AÑO 2023:
   • Archivo: nacimientos_2023_cuadro1.csv
   • Filas totales: 14
   • Columnas: 20
   • Primeras 10 columnas: ['CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, total nacional', 'columna', 'columna_1', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
  CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, total nacional columna columna_1 columna_2      columna_3           columna_4 columna_5      columna_6       columna_7 columna_8      columna_9      columna_10 columna_11     columna_12       columna_13 columna_14     columna_15   año         tipo hoja_origen
0                                                                              Grupo de edad de la madre   Total     Total       NaN            NaN  Cabecera municipal       NaN            NaN  Centro poblado       NaN            NaN  Rural disperso        NaN            NaN  Sin información        NaN            NaN  2023  nacimientos     Cuadro1
1                                                                                                    NaN     NaN   Hombres   Mujeres  Indeterminado             Hombres   Mujeres  Indeterminado         Hombres   Mujeres  Indeterminado         Hombres    Mujeres  Indeterminado          Hombres    Mujeres  Indeterminado  2023  nacimientos     Cuadro1
2                                                                                         Total Nacional   43744     22585     21155              4               22371     20927              4              89       104              0             125        124              0                0          0              0  2023  nacimientos     Cuadro1
----------------------------------------

📁 AÑO 2024:
   • Archivo: nacimientos_2024_cuadro1.csv
   • Filas totales: 14
   • Columnas: 20
   • Primeras 10 columnas: ['CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, Total Nacional', 'columna', 'columna_1', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
  CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, Total Nacional columna columna_1 columna_2      columna_3           columna_4 columna_5      columna_6       columna_7 columna_8      columna_9      columna_10 columna_11     columna_12       columna_13 columna_14     columna_15   año         tipo hoja_origen
0                                                                              Grupo de edad de la madre   Total     Total       NaN            NaN  Cabecera municipal       NaN            NaN  Centro poblado       NaN            NaN  Rural disperso        NaN            NaN  Sin información        NaN            NaN  2024  nacimientos     Cuadro1
1                                                                                                    NaN     NaN   Hombres   Mujeres  Indeterminado             Hombres   Mujeres  Indeterminado         Hombres   Mujeres  Indeterminado         Hombres    Mujeres  Indeterminado          Hombres    Mujeres  Indeterminado  2024  nacimientos     Cuadro1
2                                                                                         Total Nacional   37740     19316     18421              3               19108     18236              3              95        84              0             113        101              0                0          0              0  2024  nacimientos     Cuadro1
----------------------------------------

📁 AÑO 2025:
   • Archivo: nacimientos_2025_cuadro1.csv
   • Filas totales: 14
   • Columnas: 20
   • Primeras 10 columnas: ['CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, total nacional', 'columna', 'columna_1', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
  CUADRO 1 - Nacimientos por área de ocurrencia y sexo, según grupos de edad de la madre, total nacional columna columna_1 columna_2      columna_3           columna_4 columna_5      columna_6       columna_7 columna_8      columna_9      columna_10 columna_11     columna_12       columna_13 columna_14     columna_15   año         tipo hoja_origen
0                                                                              Grupo de edad de la madre   Total     Total       NaN            NaN  Cabecera municipal       NaN            NaN  Centro poblado       NaN            NaN  Rural disperso        NaN            NaN  Sin información        NaN            NaN  2025  nacimientos     Cuadro1
1                                                                                                    NaN     NaN   Hombres   Mujeres  Indeterminado             Hombres   Mujeres  Indeterminado         Hombres   Mujeres  Indeterminado         Hombres    Mujeres  Indeterminado          Hombres    Mujeres  Indeterminado  2025  nacimientos     Cuadro1
2                                                                                         Total Nacional  243870    125026    118832             12              123378    117229             11             579       574              0            1069       1029              1                0          0              0  2025  nacimientos     Cuadro1
----------------------------------------

📊 RESUMEN CUADRO1 - COMPARATIVA POR AÑOS:
   • Columnas por año: {'2022': 20, '2023': 20, '2024': 20, '2025': 20}
   ✅ TODOS LOS AÑOS TIENEN 20 COLUMNAS

############################################################
📋 ANALIZANDO CUADRO3
############################################################

📁 AÑO 2022:
   • Archivo: nacimientos_2022_cuadro3.csv
   • Filas totales: 1,203
   • Columnas: 23
   • Primeras 10 columnas: ['columna', 'columna_1', 'CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - float64: 3 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
   columna  columna_1                                 CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre  columna_2     columna_3 columna_4 columna_5 columna_6           columna_7 columna_8 columna_9      columna_10 columna_11 columna_12      columna_13 columna_14 columna_15       columna_16 columna_17 columna_18   año         tipo hoja_origen
0      NaN        NaN  Año Corrido 2022, preliminar - (Nacimientos ocurridos y reportados por la fuente, entre el 1 de enero y el 31 de enero de 2022)        NaN           NaN       NaN       NaN       NaN                 NaN       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2022  nacimientos     Cuadro3
1      NaN        NaN                                                                                                                 Volver al índice        NaN  Departamento       NaN       NaN       NaN           Municipio       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2022  nacimientos     Cuadro3
2      NaN        NaN                                                                               Departamento y municipio de residencia de la madre        NaN         Total     Total       NaN       NaN  Cabecera municipal       NaN       NaN  Centro poblado        NaN        NaN  Rural disperso        NaN        NaN  Sin información        NaN        NaN  2022  nacimientos     Cuadro3
----------------------------------------

📁 AÑO 2023:
   • Archivo: nacimientos_2023_cuadro3.csv
   • Filas totales: 1,204
   • Columnas: 23
   • Primeras 10 columnas: ['columna', 'columna_1', 'CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - float64: 3 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
   columna  columna_1                CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre  columna_2     columna_3 columna_4 columna_5 columna_6           columna_7 columna_8 columna_9      columna_10 columna_11 columna_12      columna_13 columna_14 columna_15       columna_16 columna_17 columna_18   año         tipo hoja_origen
0      NaN        NaN  Año Corrido 2023, preliminar - (Nacimientos ocurridos y reportados por la fuente hasta el 31 de enero de 2023)        NaN           NaN       NaN       NaN       NaN                 NaN       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2023  nacimientos     Cuadro3
1      NaN        NaN                                                                                                Volver al índice        NaN  Departamento       NaN       NaN       NaN           Municipio       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2023  nacimientos     Cuadro3
2      NaN        NaN                                                              Departamento y municipio de residencia de la madre        NaN         Total     Total       NaN       NaN  Cabecera municipal       NaN       NaN  Centro poblado        NaN        NaN  Rural disperso        NaN        NaN  Sin información        NaN        NaN  2023  nacimientos     Cuadro3
----------------------------------------

📁 AÑO 2024:
   • Archivo: nacimientos_2024_cuadro3.csv
   • Filas totales: 1,205
   • Columnas: 23
   • Primeras 10 columnas: ['columna', 'columna_1', 'CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - float64: 3 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
   columna  columna_1                       CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre  columna_2     columna_3 columna_4 columna_5 columna_6           columna_7 columna_8 columna_9      columna_10 columna_11 columna_12      columna_13 columna_14 columna_15       columna_16 columna_17 columna_18   año         tipo hoja_origen
0      NaN        NaN  Año corrido 2024, preliminar - (Nacimientos ocurridos y reportados por la fuente entre el 1 y el 31 de enero de 2024)        NaN           NaN       NaN       NaN       NaN                 NaN       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2024  nacimientos     Cuadro3
1      NaN        NaN                                                                                                       Volver al índice        NaN  Departamento       NaN       NaN       NaN           Municipio       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2024  nacimientos     Cuadro3
2      NaN        NaN                                                                     Departamento y municipio de residencia de la madre        NaN         Total     Total       NaN       NaN  Cabecera municipal       NaN       NaN  Centro poblado        NaN        NaN  Rural disperso        NaN        NaN  Sin información        NaN        NaN  2024  nacimientos     Cuadro3
----------------------------------------

📁 AÑO 2025:
   • Archivo: nacimientos_2025_cuadro3.csv
   • Filas totales: 1,220
   • Columnas: 23
   • Primeras 10 columnas: ['columna', 'columna_1', 'CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 19 columnas
      - float64: 3 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
   columna  columna_1                                CUADRO 3 - Nacimientos por área y sexo, según departamento y municipio de residencia de la madre  columna_2 columna_3 columna_4 columna_5 columna_6           columna_7 columna_8 columna_9      columna_10 columna_11 columna_12      columna_13 columna_14 columna_15       columna_16 columna_17 columna_18   año         tipo hoja_origen
0      NaN        NaN  Año corrido 2025, preliminar - (Nacimientos ocurridos y reportados por la fuente entre el 1 de enero y el 31 de julio de 2025)        NaN       NaN       NaN       NaN       NaN                 NaN       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2025  nacimientos     Cuadro3
1      NaN        NaN                                                                                                                Volver al índice        NaN       NaN       NaN       NaN       NaN                 NaN       NaN       NaN             NaN        NaN        NaN             NaN        NaN        NaN              NaN        NaN        NaN  2025  nacimientos     Cuadro3
2      NaN        NaN                                                                              Departamento y municipio de residencia de la madre        NaN     Total     Total       NaN       NaN  Cabecera municipal       NaN       NaN  Centro poblado        NaN        NaN  Rural disperso        NaN        NaN  Sin información        NaN        NaN  2025  nacimientos     Cuadro3
----------------------------------------

📊 RESUMEN CUADRO3 - COMPARATIVA POR AÑOS:
   • Columnas por año: {'2022': 23, '2023': 23, '2024': 23, '2025': 23}
   ✅ TODOS LOS AÑOS TIENEN 23 COLUMNAS

############################################################
📋 ANALIZANDO CUADRO5
############################################################

📁 AÑO 2022:
   • Archivo: nacimientos_2022_cuadro5.csv
   • Filas totales: 5,786
   • Columnas: 16
   • Primeras 10 columnas: ['columna', 'columna_1', 'CUADRO 5 - Nacimientos por persona que atendió el parto según departamento, municipio de ocurrencia y sitio del parto', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 13 columnas
      - float64: 2 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
   columna  columna_1            CUADRO 5 - Nacimientos por persona que atendió el parto según departamento, municipio de ocurrencia y sitio del parto     columna_2 columna_3 columna_4                     columna_5  columna_6 columna_7 columna_8 columna_9 columna_10 columna_11   año         tipo hoja_origen
0      NaN        NaN  Año Corrido 2022, preliminar - (Nacimientos ocurridos y reportados por la fuente, entre el 1 de enero y el 31 de enero de 2022)           NaN       NaN       NaN                           NaN        NaN       NaN       NaN       NaN        NaN        NaN  2022  nacimientos     Cuadro5
1      NaN        NaN                                                                                                                 Volver al índice  Departamento       NaN       NaN                           NaN  Municipio       NaN       NaN       NaN        NaN        NaN  2022  nacimientos     Cuadro5
2      NaN        NaN                                                                          Departamento, municipio de ocurrencia y sitio del parto           NaN       NaN     Total  Persona que atendió el parto        NaN       NaN       NaN       NaN        NaN        NaN  2022  nacimientos     Cuadro5
----------------------------------------

📁 AÑO 2023:
   • Archivo: nacimientos_2023_cuadro5.csv
   • Filas totales: 5,786
   • Columnas: 16
   • Primeras 10 columnas: ['columna', 'columna_1', 'CUADRO 5 - Nacimientos por persona que atendió el parto según departamento, municipio de ocurrencia y sitio del parto', 'columna_2', 'columna_3', 'columna_4', 'columna_5', 'columna_6', 'columna_7', 'columna_8']
   • Tipos de datos:
      - str: 13 columnas
      - float64: 2 columnas
      - int64: 1 columnas

   📝 Muestra de datos (primeras 3 filas):
   columna  columna_1 CUADRO 5 - Nacimientos por persona que atendió el parto según departamento, municipio de ocurrencia y sitio del parto     columna_2 columna_3 columna_4                     columna_5  columna_6 columna_7 columna_8 columna_9 columna_10 columna_11   año         tipo hoja_origen
0      NaN        NaN        Año Corrido 2023, preliminar - (Nacimientos ocurridos y reportados por la fuente hasta el 31 de enero de 2023)           NaN       NaN       NaN                           NaN        NaN       NaN       NaN       NaN        NaN        NaN  2023  nacimientos     Cuadro5